export const ENCOUNTERS_BY_POKEMON: {[key: string]: string[]} = {
  pagie: ['Paper World - Cave'],
  nixox: ['Faroff Town - Land'],
  playne: ['Faroff Town - Land'],
  flufamb: ['Route 3 - Land'],
  neonee: ['Seas - Land'],
  uncrow: ['Graveyard 3F - Cave'],
  smoball: ['Frosty Forest - Land'],
  iceis: ['Temple of the Ice Age - Cave'],
  snowdoge: ['Temple of the Ice Age - Cave'],
  snuggice: ['Frosty Forest - Land'],
  vanillite: ['Frosty Forest 2 - Land'],
  pengui: ['Arctic - Water'],
  elastim: ['Route 2 - LandDay'],
  doit: ['Seaside Village - Land'],
  artsy: ['Eternal Forest - Land'],
  rubbero: ['Junkyard - Land'],
  brico: ['Eternal Forest - Land'],
  undlouis: ['Graveyard 3F - Cave'],
  earring: ['Route 4 - LandNight'],
  guttsu: ['Route 2 - LandNight'],
  enderite: ['Route 2 - LandNight'],
  cosmock: ['Miam Cavern 2 - Cave'],
  chipit: ['Miam Cavern 2 - Cave'],
  goom: ['Miam Cavern 2 - Cave'],
  cuplet: ['Miam Cavern 2 - Cave'],
  steamea: ['Miam Cavern BF - Cave'],
  lickitung: ['Miam Cavern 2 - Cave'],
  farfetchd: ['Miam Cavern - Cave'],
  swirlix: ['Miam Cavern BF - Cave'],
  geodude: ['MAP781 - Land'],
  rubadubb: ['Cybergate City - Water'],
  bairy: ['Faroff Town - Land'],
  tideno: ['Seas - Land'],
  gooseling: ['Seaside Village - Land'],
  bottleo: ['Trial Caverns - OldRod'],
  oregi: ['Safari Zone - Water'],
  carvanha: ['Route 4 - OldRod'],
  lotad: ['Misty Cavern - OldRod'],
  superrod: ['Wackissic Park - GoodRod'],
  sharpedo: ['Temple of the Shark Age - GoodRod'],
  lombre: ['Seaside Village - GoodRod'],
  frillish: ['Route 7 - GoodRod'],
  canyou: ['Wood World - Land'],
  floatube: ['Route Victor - Water'],
  battie: ['Route Victor - Water'],
  staryu: ['Seaside Cavern - GoodRod'],
  buizel: ['Seas - Water'],
  finneon: ['Seas - OldRod'],
  mopockit: ['Route 3 (2) - Land'],
  clavies: ['Cyber World - Cave'],
  creemo: ['Route 5 - Land'],
  mousee: ['Tech World - Cave'],
  hompuff: ['Mount Voormithadreth - Land'],
  bouncect: ['Route 3 - Land'],
  bulbight: ['Temple of the Modern Age - Cave'],
  timbito: ['Route 3 - Land'],
  storactus: ['Ankh Desert - Cave'],
  patima: ['Ankh Desert - Cave'],
  mexigust: ['Ankh Desert - Cave'],
  baifre: ['Ankh  Ruins BF - Cave'],
  roven: ['Ankh Desert - Cave'],
  palmetric: ['Safari Zone - Land'],
  dusite: ['Temple of the Iron Age - Cave'],
  coyot: ['Ankh Desert - Cave'],
  snakeny: ['Ankh Desert - Cave'],
  tuterpill: ['Ankh  Ruins BF - Cave'],
  boxy: ['Ankh  Ruins BF - Cave'],
  gargie: ['The Library - Cave'],
  pareyemid: ['Rock World - Cave'],
  mummeem: ['Ankh ruins - Cave'],
  eleoler: ['Steam World - Land'],
  swanaper: ['Paper World - Cave'],
  squirtle: ['Dewdrop Cavern - Cave'],
  oshawott: ['Dewdrop Cavern - Cave'],
  totodile: ['Dewdrop Cavern - Cave'],
  piplup: ['Dewdrop Cavern - Cave'],
  mudkip: ['Dewdrop Cavern - Cave'],
  froakie: ['Dewdrop Cavern - Cave'],
  juzt: ['Temple of the Extinction Age - Cave'],
  namino: ['Magic World - Cave'],
  chairy: ['Grass World - Land'],
  tauros: ['Safari zone 4 - Land'],
  miltank: ['Food World - Cave'],
  jetcraft: ['Tech World - Cave'],
  bongorilla: ['Safari Zone - Land'],
  rhyhorn: ['Safari Zone - Cave'],
  pyroar: ['Thermal Cavern - Cave'],
  oranguru: ['Safari Zone - Land'],
  passimian: ['Alola Cave - Cave'],
  gordrarm: ['Safari Zone - Land'],
  kangaskhan: ['Safari Zone - Land'],
  chansey: ['The Dungeon - Cave'],
  mantyke: ['Safari Zone - Water'],
  bruxish: ['Trial Caverns - GoodRod'],
  fabreel: ['Safari Zone - Water'],
  dratini: ['Safari Zone - GoodRod'],
  cutehulhu: ['Underwater - Water'],
  spotni: ['Faroff Town - Land'],
  machetit: ['Temple of the Iron Age - Cave'],
  zomby: ['Graveyard 3F - Cave'],
  charmander: ['Scorching Cavern - Cave'],
  cyndaquil: ['Scorching Cavern - Cave'],
  tepig: ['Scorching Cavern - Cave'],
  torchic: ['Scorching Cavern - Cave'],
  chimchar: ['Scorching Cavern - Cave'],
  fennekin: ['Scorching Cavern - Cave'],
  snivy: ['Petal Grove - Cave'],
  chikorita: ['Petal Grove - Cave'],
  chespin: ['Petal Grove - Cave'],
  bulbasaur: ['Petal Grove - Cave'],
  treecko: ['Petal Grove - Cave'],
  turtwig: ['Petal Grove - Cave'],
  pidgey: ['Route 29 Copy - LandDay'],
  taillow: ['ROUTE 104 - Land'],
  starly: ['Flock Grotto - Cave'],
  hoothoot: ['Route 29 Copy - LandNight'],
  fletchling: ['Flock Grotto - Cave'],
  spearow: ['Route 23 down - Land'],
  doduo: ['Safari zone 4 - Land'],
  pidove: ['Flock Grotto - Cave'],
  rattata: ['Route 29 Copy - LandNight'],
  zigzagoon: ['ROUTE 104 - Land'],
  bidoof: ['Rodent Grotto - Cave'],
  sentret: ['Route 29 Copy - LandNight'],
  bunnelby: ['Rodent Grotto - Cave'],
  patrat: ['Rodent Grotto - Cave'],
  caterpie: ['VIRIDIAN FOREST - LandNight'],
  weedle: ['VIRIDIAN FOREST - LandNight'],
  wurmple: ['ROUTE 104 - Land'],
  kricketot: ['Crawly Grotto - Cave'],
  sewaddle: ['Crawly Grotto - Cave'],
  scatterbug: ['Crawly Grotto - Cave'],
  venipede: ['Crawly Grotto - Cave'],
  mawile: ['Misty Cavern - Cave'],
  spritzee: ['Misty Cavern - Cave'],
  sableye: ['Volcano Interior - Cave'],
  flabebe: ['Misty Cavern - Cave'],
  audino: ['The Dungeon - Cave'],
  absol: ['MAP781 - Land'],
  kirlia: ['Misty Cavern - Cave'],
  onix: ['Rock World - Cave'],
  diglett: ["Diglett's Cave B - Cave"],
  carbink: ['Rocky Crevase - Cave'],
  roggenrola: ['Rocky Crevase - Cave'],
  aron: ['Temple of the Iron Age - Cave'],
  higukasai: ['Witch Island - Land'],
  akanezaki: ['Witch Island - Land'],
  higurachie: ['Witch Island - Land'],
  higuirie: ['Witch Island - Land'],
  tomitake: ['Witch Island - Land'],
  oishigurashi: ['Witch Island - Land'],
  natsumiyoshi: ['Witch Island - Land'],
  higukeiichi: ['Witch Island - Land'],
  higusatoko: ['Witch Island - Land'],
  mionzaki: ['Witch Island - Land'],
  akasaka: ['Witch Island - Land'],
  shionzaki: ['Witch Island - Land'],
  cacnea: ['Arid Cavern - Cave'],
  darumaka: ['Arid Cavern - Cave'],
  hippopotas: ['Arid Cavern - Cave'],
  yamask: ['Arid Cavern - Cave'],
  trapinch: ['Arid Cavern - Cave'],
  baltoy: ['Arid Cavern - Cave'],
  sandshrew: ['Route 23 down - Land'],
  skorupi: ['Hive BF - Cave'],
  sigilyph: ['Arid Cavern - Cave'],
  fedoraz: ['Graveyard - Land'],
  ijusgetsbigger: ['Route 5 - Land'],
  grasses: ['Route 8 - Land'],
  microette: ['Echo Cavern - Cave'],
  feebas: ['Route Victor - OldRod'],
  orscine: ['Trial Caverns - GoodRod'],
  krabby: ['Ship BF1 - Cave'],
  spheal: ['Sea Salt Cave - Cave'],
  slowpoke: ['Cerulean Cave 3 - GoodRod'],
  corphish: ['Sea Salt Cave - Cave'],
  seel: ['Seafoam Islands 5 - Water'],
  wingull: ['ROUTE 104 - Water'],
  shellder: ['Ship BF1 - Cave'],
  cubone: ['Pokemon Tower Floor 7 - Cave'],
  duskull: ['Spooky Woods - Land'],
  murkrow: ['Gold Tower F3 - Cave'],
  shuppet: ['Graveyard - Land'],
  misdreavus: ['Haunted Mansion - Cave'],
  gastly: ['Pokemon Tower Floor 7 - Cave'],
  drummin: ['Graveyard 3F - Cave'],
  spooksheet: ['Haunted Mansion - Cave'],
  gueriest: ['Ghost World - Cave'],
  haicaw: ['Zombie World - Cave'],
  tvirusby: ['Graveyard 2F - Cave'],
  macat: ['Graveyard 2F - Cave'],
  diebbuk: ['Graveyard 3F - Cave'],
  dedfishe: ['Temple of the Shark Age - GoodRod'],
  pumpkaboo: ["Hallow's Woods - Land"],
  phantump: ["Hallow's Woods - Land"],
  drifloon: ['Spooky Woods - Land'],
  litwick: ['Spooky Woods - Land'],
  arod: ['Route 6 - Land'],
  prisy: ['Route 8 - Land'],
  speakerro: ['Route 6 - Land'],
  canvast: ['Paper World - Cave'],
  anol: ['Divine World - Cave'],
  ditto: ['Mysterious Dungeon - Cave'],
  plastolphin: ['Synth City - GoodRod'],
  luvdisc: ['Venus - Cave'],
  shellos: ['Misty Cavern - Cave'],
  gastrodon: ['MAP781 - Land'],
  alomomola: ['Synth City - GoodRod'],
  maghat: ['Route 8 - Land'],
  mellown: ['Grass World - Land'],
  lamcoud: ['Wind World - Cave'],
  melonboy: ['Eternal Forest - Land'],
  basculin: ['Synth City - GoodRod'],
  remoraid: ['Seaside Cavern - GoodRod'],
  gyarados: ['Thermal Cavern - GoodRod'],
  inkay: ['Surfin City - GoodRod'],
  swablu: ['Southern Island - Land'],
  natu: ['Southern Island - Land'],
  drowzee: ['ROUTE 11 left - Land'],
  munna: ['Southern Island - Land'],
  espurr: ['Southern Island - Land'],
  kadabra: ['Magic World - Cave'],
  gothita: ['Victory Chamber - Cave'],
  flowjaw: ['Temple of the Shark Age - Cave'],
  spongee: ['Seaside Cavern - Cave'],
  zyklas: ['Steam World - Land'],
  poliwag: ['Cerulean Cave 3 - GoodRod'],
  poliwhirl: ['Cerulean Cave 3 - GoodRod'],
  tentacool: ['ROUTE 21 - Water'],
  snover: ['Frosty Forest 2 - Land'],
  bergmite: ['Frost Island - Land'],
  smoochum: ['Frosty Forest 2 - Land'],
  cubchoo: ['Frost Island - Land'],
  delibird: ['Frosty Forest 2 - Land'],
  wolfman: ['Burning Tower - Cave'],
  elekid: ['Shocky Cavy - Cave'],
  pikachu: ['Hidden Basement - Cave'],
  joltik: ['Temple of the Modern Age - Cave'],
  blitzle: ['Shocky Cavy - Cave'],
  tynamo: ['Temple of the Modern Age - Cave'],
  plusle: ['Victory Chamber - Cave'],
  pachirisu: ['Victory Chamber - Cave'],
  dedenne: ['Shocky Cavy - Cave'],
  minun: ['Victory Chamber - Cave'],
  magby: ['ROUTE 9 - Land'],
  ponyta: ['ROUTE 22 - Land'],
  houndour: ['Flare Island - Land'],
  vulpix: ['Pokemon Mansion BF - Cave'],
  growlithe: ['Pokemon Mansion BF - Cave'],
  fletchinder: ['Flare Island - Land'],
  pansear: ['Humid Forest - Land'],
  numel: ['Flare Island - Land'],
  torkoal: ['Flare Valley - Cave'],
  slugma: ['Flare Island - Land'],
  cryogonal: ['Temple of the Ice Age - Cave'],
  swinub: ['Frost Island - Land'],
  piloswine: ['Frost Valley - Cave'],
  sneasel: ['Frost Valley - Cave'],
  glalie: ['Frost Valley - Cave'],
  snorunt: ['Frost Island - Land'],
  amaura: ['Prehistoric Island Gate - Land'],
  cloyster: ['Frost Island - Land'],
  smoman: ['Temple of the Ice Age - Cave'],
  coolor: ['Seaside Cavern - Cave'],
  cocaiturd: ['Poison World - Cave'],
  chinchou: ['VERMILION CITY - GoodRod'],
  wooper: ['ROUTE 12 - Water'],
  quagsire: ['Seaside Cavern - GoodRod'],
  wailmer: ['Seaside Cavern - GoodRod'],
  qwilfish: ['ROUTE 12 - GoodRod'],
  budsee: ['Echo Cavern - Cave'],
  whismur: ['Echo Cavern - Cave'],
  chimecho: ['Echo Cavern - Cave'],
  noibat: ['Temple of the End Age - Cave'],
  kricketune: ['Echo Cavern - Cave'],
  jigglypuff: ['ROUTE 3 - Land'],
  oddish: ['ROUTE 15 right - Land'],
  bellsprout: ['ROUTE 15 right - Land'],
  paras: ['Safari zone 3 - Land'],
  exeggcute: ['Safari zone 4 - Land'],
  hoppip: ['Route 29 Copy - LandDay'],
  sunkern: ['ROUTE 24 - LandDay'],
  seedot: ['Grass Place - Cave'],
  shroomish: ['Grass Place - Cave'],
  budew: ['Grass Place - Cave'],
  cherubi: ['Grass Place - Cave'],
  pansage: ['Humid Forest - Land'],
  petilil: ['Grass Place - Cave'],
  tropius: ['Hidden Research Area - Land'],
  foongus: ['Grass Place - Cave'],
  tangela: ['ROUTE 21 - Land'],
  cottonee: ['Grass Place - Cave'],
  ferroseed: ['Grass Place - Cave'],
  skiddo: ['Grass Place - Cave'],
  carnivine: ['Venus - Cave'],
  mareep: ['ROUTE 10 - Land'],
  belcalf: ['The Ranch - Land'],
  shinx: ['The Ranch - Land'],
  spoink: ['The Ranch - Land'],
  furfrou: ['The Ranch - Land'],
  poochyena: ['ROUTE 104 - Land'],
  yeerby: ['The Ranch - Land'],
  nidoranfe: ['Safari zone 4 - Land'],
  nidoranma: ['Safari zone 4 - Land'],
  purrloin: ['Field - Land'],
  stantler: ['Field - Land'],
  skitty: ['Field - Land'],
  seviper: ['Field - Land'],
  zangoose: ['Field - Land'],
  zubat: ['Temple of the End Age - Cave'],
  gligar: ['Ground World - Cave'],
  phanpy: ['The Cave Cave - Cave'],
  woobat: ['The Cave Cave - Cave'],
  drilbur: ['The Cave Cave - Cave'],
  sandile: ['The Cave Cave - Cave'],
  wynaut: ['The Cave Cave - Cave'],
  goldeen: ['Cerulean Cave 3 - GoodRod'],
  horsea: ['Seafoam Islands 5 - GoodRod'],
  seadra: ['ROUTE 21 - GoodRod'],
  barboach: ['Seaside Cavern - GoodRod'],
  starmie: ['Seaside Cavern - GoodRod'],
  otyab: ['Junkyard - Land'],
  tiroar: ['Temple of the End Age - Cave'],
  boxo: ['Paper World - Cave'],
  gummi: ['Food World - Cave'],
  recyclat: ['Plastic World - Cave'],
  shattarate: ['Shock Valley - Cave'],
  synthite: ['Plastic World - Water'],
  grimer: ['Pokemon Mansion BF - Cave'],
  koffing: ['Pokemon Mansion BF - Cave'],
  stunky: ['Store House - Cave'],
  gulpin: ['Store House - Cave'],
  trubbish: ['Store House - Cave'],
  magnemite: ['Temple of the Modern Age - Cave'],
  carpla: ['The Library - Cave'],
  seatie: ['Haunted Mansion - Cave'],
  jgolett: ['Abandoned Mansion - Cave'],
  brigo: ['Abandoned Mansion - Cave'],
  matzio: ['Abandoned Mansion - Cave'],
  eyat: ['Abandoned Mansion - Cave'],
  dreidelspi: ['Abandoned Mansion - Cave'],
  hanukkora: ['Abandoned Mansion - Cave'],
  davistar: ['Abandoned Mansion - Cave'],
  larvitar: ['Abandone Town - Land'],
  goomy: ['Abandone Town - Land'],
  bronzor: ['Abandone Town - Land'],
  tympole: ['Abandone Town - Land'],
  bricken: ['Temple of the Stone Age - Cave'],
  pinsir: ['Safari zone 2 - Land'],
  stunfisk: ['Abandone Town - Land'],
  machop: ['Ship BF1 - Cave'],
  makuhita: ['Abandoned gym - Cave'],
  meditite: ['Abandoned gym - Cave'],
  croagunk: ['Abandoned gym - Cave'],
  heracross: ['Abandoned gym - Cave'],
  sawk: ['Abandoned gym - Cave'],
  throh: ['Abandoned gym - Cave'],
  scraggy: ['Abandoned Gym BF - Cave'],
  timburr: ['Abandoned Gym BF - Cave'],
  mienfoo: ['Abandoned Gym BF - Cave'],
  pancham: ['Abandoned Gym BF - Cave'],
  hawlucha: ['Abandoned Gym BF - Cave'],
  hitmonchan: ['Abandoned Gym BF - Cave'],
  hitmonlee: ['Abandoned Gym BF - Cave'],
  fanin: ['Temple of the Modern Age - Cave'],
  espionot: ['Upgrade Cave BF - Cave'],
  sonotech: ['Cyber World - Cave'],
  nanos: ['Upgrade Cave BF - Cave'],
  tweeter: ['Upgrade Cave BF - Cave'],
  myosmic: ['Upgrade Cave - Cave'],
  feborius: ['DEEP WEB - Cave'],
  porygon: ['Cyber World - Cave'],
  beldum: ['Upgrade Cave BF - Cave'],
  klink: ['Upgrade Cave BF - Cave'],
  magneton: ['Shock Valley - Cave'],
  electrode: ['Mysterious Dungeon - Cave'],
  porygon2: ['DEEP WEB - Cave'],
  litleo: ['Field - Land'],
  lillipup: ['Field - Land'],
  ekans: ['MAP781 - Land'],
  electrike: ['Field - Land'],
  deerling: ['Field - Land'],
  buneary: ['Field - Land'],
  meowth: ['ROUTE 7 - Land'],
  mankey: ['Ship BF1 - Cave'],
  aipom: ['Field - Land'],
  snubbull: ['Field - Land'],
  teddiursa: ['Field - Land'],
  riolu: ['Field - Land'],
  combee: ['MAP781 - Land'],
  durant: ['Hive - Cave'],
  ledyba: ['Route 29 Copy - LandDay'],
  spinarak: ['Route 29 Copy - LandNight'],
  pineco: ['Hive - Cave'],
  scyther: ['Safari Zone - Cave'],
  yanma: ['Prehistoric Island Gate - Land'],
  surskit: ['MAP781 - Land'],
  nincada: ['Hive BF - Cave'],
  volbeat: ['Hive BF - Cave'],
  burmy: ['Hive BF - Cave'],
  shuckle: ['Hive BF - Cave'],
  illumise: ['Hive BF - Cave'],
  dwebble: ['Hive BF - Cave'],
  larvesta: ['Volcano Shrine - Land'],
  venonat: ['Safari zone 4 - Land'],
  karrablast: ['Hive BF - Cave'],
  shelmet: ['Hive BF - Cave'],
  electabuzz: ['Shock Valley - Cave'],
  manectric: ['Thunder Shrine - Land'],
  galvantula: ['Thunder Shrine - Land'],
  zebstrika: ['Thunder Shrine - Land'],
  eelektrik: ['Shock Valley - Cave'],
  magmar: ['Temple of the Extinction Age - Cave'],
  houndoom: ['Flare Valley - Cave'],
  camerupt: ['Temple of Land - Cave'],
  magcargo: ['Temple of the Extinction Age - Cave'],
  mrmime: ['ROUTE 21 - Land'],
  girafarig: ['Three Lake Island - Land'],
  spinda: ['Chaos World - Cave'],
  castform: ['Three Lake Island - Land'],
  zorua: ['Victory Chamber - Cave'],
  klefki: ['Moon Island - LandDay'],
  skwovet: ['Galar Cave - Cave'],
  mimejr: ['Liberty Island - Land'],
  bonsly: ['Liberty Island - Land'],
  glameow: ['Liberty Island - Land'],
  minccino: ['Liberty Island - Land'],
  helioptile: ['Temple of the Modern Age - Cave'],
  munchlax: ['Liberty Island - Land'],
  happiny: ['The Dungeon - Cave'],
  solosis: ['Victory Chamber - Cave'],
  emolga: ['Victory Chamber - Cave'],
  elgyem: ['Victory Chamber - Cave'],
  honedge: ['Victory Chamber - Cave'],
  axew: ['Temple of the End Age - Cave'],
  archen: ['Carnivorous Exhibit - Land'],
  shieldon: ['Prehistoric Island Gate - Land'],
  kabuto: ['Shallows Cave - Cave'],
  anorith: ['Shallows Cave - Water'],
  lileep: ['Shallows Cave - Cave'],
  omanyte: ['Shallows Cave - Water'],
  tirtouga: ['Regi Isles - GoodRod'],
  relicanth: ['Shallows Cave - GoodRod'],
  elding: ['Temple of the Ice Age - Cave'],
  raticate: ['MAP781 - Land'],
  unfezant: ['The Slums - Cave'],
  hoverot: ['Tech World - Cave'],
  beetarp: ['The Slums - Cave'],
  golbat: ['Voormithadreth - Cave'],
  muk: ['Poison World - Cave'],
  praticate: ['Poison World - Cave'],
  skarmory: ['Volcano Interior - Cave'],
  magmocket: ['Temple of the Extinction Age - Cave'],
  druddigon: ['Dragon World - Cave'],
  firepire: ['Fire World - Cave'],
  drifblim: ['Windy Plateau - Land'],
  bouffalant: ['Windy Plateau - Land'],
  jumpluff: ['Windy Plateau - Land'],
  vullaby: ['Windy Plateau - Land'],
  rufflet: ['Windy Plateau - Land'],
  swoobat: ['Sewers (Drained) - Cave'],
  bottleodrake: ['Plastic World - GoodRod'],
  otyash: ['Poison World - Cave'],
  teskare: ['Zombie World - Cave'],
  sola: ['Surface of the Sun - Cave'],
  grinix: ['Route 10 - Land'],
  behemist: ['Steam World - Land'],
  euphoreye: ['Route 10 - Land'],
  kecleon: ['Liberty Cavern - Cave'],
  golett: ['Liberty Cavern - Cave'],
  bagon: ['Liberty Cavern - Cave'],
  dunsparce: ['Liberty Cavern - Cave'],
  pawniard: ['Liberty Cavern - Cave'],
  gible: ['Temple of the End Age - Cave'],
  sushish: ['Route Victor - GoodRod'],
  clauncher: ['Ocean - GoodRod'],
  skrelp: ['Ocean - GoodRod'],
  barab: ['MAP781 - Land'],
  radien: ['Temple of the Modern Age - Cave'],
  zilly: ['Nuclear Forest - Land'],
  creeposs: ['Nuclear Forest - Land'],
  banor: ['Nuclear Forest - Land'],
  wdeino: ['Beneath the Camp - Cave'],
  rodac: ['Nuclear Forest - Land'],
  doratgon: ['Nuclear Forest - Land'],
  raydiat: ['Cherno City - GoodRod'],
  psyduck: ['Cerulean Cave 3 - GoodRod'],
  marill: ['ROUTE 104 - Land'],
  binacle: ['Misty Cavern - Cave'],
  clamperl: ['Misty Cavern - Cave'],
  corsola: ['VERMILION CITY - Water'],
  encyclodia: ['Paper World - Cave'],
  willisp: ['The Library - Cave'],
  unown: ['Gold Tower F3 - Cave'],
  cosmix: ['Eternal Forest - Land'],
  chatot: ['The Library - Cave'],
  milotic: ['Route 11 - GoodRod'],
  slakoth: ['Humid Forest - Land'],
  ducklett: ['Humid Forest - Land'],
  panpour: ['Humid Forest - Land'],
  eevee: ["Bill's Garden - Land"],
  attot: ['Temple of the Modern Age - Cave'],
  nukomb: ['Nuclear Forest - Cave'],
  frankenspook: ['Zombie World - Cave'],
  willost: ['Ghost World - Cave'],
  devio: ['Pagan Woods - Land'],
  anguar: ['Arcania City - Land'],
  bushin: ['Temple of the Iron Age - Cave'],
  gublin: ['Pagan Woods - Land'],
  acies: ['Temple of the End Age - Cave'],
  lun: ['Safari Zone - GoodRod'],
  goatkun: ['Chaos World - Cave'],
  steelix: ['Temple of the Iron Age - Cave'],
  turbind: ['Tech World - Cave'],
  lightulb: ['Shock Valley - Cave'],
  ampharos: ['Gold Tower F3 - Cave'],
  plasbul: ['Iron Works - Cave'],
  scizor: ['Iron Works - Cave'],
  altaria: ['Sky Pillar - Cave'],
  volcarona: ['Fire World - Cave'],
  sunflora: ['??? - Cave'],
  heliolisk: ['The Sun - Cave'],
  solrock: ['Cosmic World - Cave'],
  noctowl: ['MAP781 - Land'],
  hypno: ['Moon Island - LandNight'],
  deino: ['Temple of the End Age - Cave'],
  honchkrow: ['Moon Island - LandNight'],
  clefairy: ['MT. MOON - Cave'],
  lunatone: ['Cosmic World - Cave'],
  haunter: ['Ghost World - Cave'],
  xatu: ['Gold Tower F3 - Cave'],
  gorale: ['Wind World - Cave'],
  doita: ['Magma World - Cave'],
  onigi: ['Route 11 - Land'],
  lightsy: ['Arcania City - Land'],
  drubber: ['Route 11 - Water'],
  splissplash: ['Route 11 - Water'],
  carolden: ['Route 11 - Water'],
  dragonair: ['Safari zone 4 - GoodRod'],
  warshin: ['Temple of Sea - Cave'],
  atmosro: ['Route 12 - Land'],
  sateli: ['Cosmic World - Cave'],
  wheelus: ['Dragon World - Cave'],
  pixall: ['Data Mines - Cave'],
  combug: ['Data Mines - Cave'],
  smirtsnek: ['Data Mines - Cave'],
  viriv: ['Virus World - Cave'],
  fireall: ['Cyber World - Cave'],
  pixension: ['Cyber World - Cave'],
  buglitch: ['Cyber World - Cave'],
  smirtrsnekek: ['Tech World - Cave'],
  dragurve: ['Corrupted Crags - Cave'],
  virurm: ['Forgotten Depths - Cave'],
  poryrus: ['Virus World - Cave'],
  poryrusz: ['Glitch - Cave'],
  thereisonlyhell: ['Beneath the Camp - Cave'],
  alliswell: ['Glitch - Cave'],
  trojorse: ['Virus World - Cave'],
  malworm: ['Virus World - Cave'],
  tyrunt: ['Hidden Path - Land'],
  cranidos: ['Carnivorous Exhibit - Land'],
  aerodactyl: ['Temple of the Stone Age - Cave'],
  gachamber: ['Poison World - Cave'],
  infernace: ['Beneath the Camp - Cave'],
  nukreep: ['Nuclear World - Cave'],
  tenablerus: ['Ghost World - Cave'],
  chandelure: ['Beneath the Camp - Cave'],
  wizcap: ['Magic World - Cave'],
  sixsnek: ['Temple of the End Age - Cave'],
  bargear: ['Arcania City - Land'],
  darkyo: ['Pagan Woods - Land'],
  snatan: ['Magic World - Cave'],
  dargouille: ['Mount Voormithadreth - Land'],
  cummunculus: ['Wind World - Cave'],
  univax: ['Cosmic World - Cave'],
  horrorux: ['Victory Road - Cave'],
  brickor: ['Shock Valley - Cave'],
  diebbyuk: ['Ghost World - Cave'],
  floette: ['Eternal Forest - Land'],
  ursaring: ['Eternal Forest - Land'],
  pidgeot: ['MAP781 - Land'],
  ryulung: ['Divine World - Cave'],
  eldragon: ['Chaos World - Cave'],
  angeist: ['Divine World - Cave'],
  stando: ['Victory Road - Land'],
  coraut: ['Chaos World - Water'],
  eldcraftian: ['Chaos World - GoodRod'],
  spiritomb: ['Cave - Cave'],
  sphinxiant: ['RuinsRuinsRuinsRuinsRuinsRuinsRuinsRuins - Cave'],
  nitegant: ['Outer Path - Cave'],
  aexeggutor: ['Grass World - Land'],
  arattata: ['Alola Island - Land'],
  ameowth: ['Alola Island - Land'],
  asandshrew: ['Alola Island - Land'],
  avulpix: ['Alola Island - Land'],
  agrimer: ['Alola Island - Land'],
  huntail: ['Underwater - Water'],
  gorebyss: ['Underwater - Water'],
  bmagikarp: ['Water World - GoodRod'],
  lanturn: ['VERMILION CITY - GoodRod'],
  wphantump: ["Hallow's Woods - Land"],
  twickotweet: ['Haunted Mansion - Cave'],
  mimikyu: ['Haunted Mansion - Cave'],
  amagikarp: ['Arctic - GoodRod'],
  ningice: ['Temple of Sea - Water'],
  dewgong: ['Seafoam Islands 5 - Water'],
  adratini: ['Arctic - GoodRod'],
  wendigi: ['Mountains of Insanity - Cave'],
  snowpil: ['Temple of the Ice Age - Cave'],
  burgite: ['Arctic - Cave'],
  walrein: ['Arctic - Cave'],
  prinplup: ['Arctic - Cave'],
  pengemperor: ['Arctic - Cave'],
  froskoon: ['Arctic - Cave'],
  rhemorice: ['Sloggoth Pits - Cave'],
  empoleon: ['Arctic - Cave'],
  aurorus: ['Temple of the Ice Age - Cave'],
  beartic: ['Arctic - Cave'],
  omegnown: ['Divine World - Cave'],
  icendless: ['Chaos World - Water'],
  eldone: ['Temple of the Ice Age - Cave'],
  kingellow: ['Mountains of Insanity - Cave'],
  albinguin: ['Mountains of Insanity - Cave'],
  wendigore: ['Mountains of Insanity - Cave'],
  eldri: ['Mountains of Insanity - Cave'],
  yungoos: ['Alolan Cave - Cave'],
  morelull: ['Alolan Cave - Cave'],
  crabrawler: ['Alolan Cave - Cave'],
  pikipek: ['Alolan Cave - Cave'],
  wishiwashi: ['Alolan Cave - Cave'],
  grubbin: ['Alolan Cave - Cave'],
  cutiefly: ['Alolan Cave - Cave'],
  rockruff: ['Alolan Cave - Cave'],
  stufful: ['Alolan Cave - Cave'],
  mudbray: ['Alolan Cave - Cave'],
  bounsweet: ['Alolan Cave - Cave'],
  fomantis: ['Trial Caverns - Cave'],
  adiglett: ['Alola Cave - Cave'],
  ageodude: ['Temple of the Modern Age - Cave'],
  akoffing: ['Alola Cave - Cave'],
  aparas: ['Alola Cave - Cave'],
  mareanie: ['Trial Caverns - OldRod'],
  salandit: ['Flare Valley - Cave'],
  dewpider: ['Alola Cave - Cave'],
  comfey: ['Trial Caverns - Cave'],
  wimpod: ['Alola Cave - Cave'],
  sandygast: ['Trial Caverns - Cave'],
  pyukumuku: ['Trial Caverns - Water'],
  oricorio: ['Trial Caverns - Cave'],
  minior: ['Trial Caverns - Cave'],
  komala: ['Alola Cave - Cave'],
  turtonator: ['Thermal Cavern - Cave'],
  drampa: ['Dragon World - Cave'],
  dhelmise: ['Alola Cave - Cave'],
  jangmoo: ['Temple of the End Age - Cave'],
  togedemaru: ['Shocky Cavy - Cave'],
  indhead: ['Zombie World - Cave'],
  steamist: ['Chaos World - Water'],
  baxbak: ['Zombie World - Cave'],
  bgyarados: ['Water World - GoodRod'],
  cultulzu: ['Temple of Sea - Cave'],
  seahog: ['Temple of Sea - Cave'],
  absorsponge: ['Temple of Sea - Cave'],
  dragonite: ['Dragon World - Cave'],
  gaghocean: ['Temple of Sea - Water'],
  heruptin: ['Magma World - Cave'],
  sandolcano: ['Temple of Land - Cave'],
  flygon: ['Ground World - Cave'],
  claydol: ['Ground World - Cave'],
  salamence: ['Dragon World - Cave'],
  hydreigon: ['Temple of the Dark Age - Cave'],
  metagross: ['Sky Pillar - Cave'],
  archango: ['Fighting World - Cave'],
  orderymid: ['Divine World - Cave'],
  spirus: ['Ultra Space - Cave'],
  clefable: ['The Moon - Cave'],
  azumarill: ['The Moon - Cave'],
  lunound: ['The Moon? - Cave'],
  solaioss: ['Surface of the Sun - Cave'],
  lunighton: ['The Moon - Cave'],
  moonse: ['The Moon? - Cave'],
  rogodo: ['Divine World - Cave'],
  lunafake: ['The Moon? - Cave'],
  mooneast: ['The Moon? - Cave'],
  fonighton: ['The Moon? - Cave'],
  bubblet: ['Route -1 - Water'],
  slinka: ['Route -1 - Land'],
  drafly: ['Route -1 - Land'],
  nothyp: ['Route -1 - Land'],
  coneet: ['Route -1 - Land'],
  paintip: ['Route -1 - Land'],
  nymphad: ['Life - Land'],
  cornird: ['Route -1 - Land'],
  anguille: ['Hidden Research Area - Water'],
  baitish: ['Route -1 - OldRod'],
  pmagikarp: ['Route -1 - GoodRod'],
  ribombee: ['Trial Caverns - Cave'],
  whimsicott: ['Life - Land'],
  shiinotic: ['Life - Land'],
  goblord: ['Chamber of the Ages - Cave'],
  gengar: ['Death - Cave'],
  mladee: ['Temple of the Dark Age - Cave'],
  novais: ['Cosmic World - Cave'],
  darkole: ['Cosmic World - Cave'],
  mawcar: ['Chaos World - Water'],
  zodiacunown: ['Zodiac Temple - Cave'],
  tridler: ['Mars Mine - Cave'],
  ayyliem: ['Mars Mine - Cave'],
  ufowoah: ['Mars - Cave'],
  birbley: ['Mars - Cave'],
  cragite: ['Something Cave - Cave'],
  stalig: ['Something Cave - Cave'],
  wock: ['Something Cave - Cave'],
  cristo: ['Something Cave - Cave'],
  cybirb: ['Mars Mine - Cave'],
  tiwisone: ['Rock World - Cave'],
  facefugger: ['Mars Mine - Cave'],
  facarveel: ['Regi Isles - Water'],
  crustle: ['Temple of the Stone Age - Cave'],
  eyeluminid: ['Temple of the Stone Age - Cave'],
  vanillish: ['Temple of the Ice Age - Cave'],
  kabutops: ['Temple of the Stone Age - Cave'],
  omastar: ['Temple of the Stone Age - Cave'],
  armaldo: ['Temple of the Stone Age - Cave'],
  aggron: ['Temple of the Iron Age - Cave'],
  warchon: ['Wind World - Cave'],
  magnezone: ['Temple of the Iron Age - Cave'],
  bushidon: ['Zombie World - Cave'],
  snofistor: ['Temple of the Ice Age - Cave'],
  frostear: ['Temple of the Ice Age - Cave'],
  vanilluxe: ['Temple of the Ice Age - Cave'],
  mamoswine: ['Temple of the Ice Age - Cave'],
  haxorus: ['Dragon World - Cave'],
  aegislash: ['Chamber of the Ages - Cave'],
  malamar: ['Temple of the Dark Age - Cave'],
  majin: ['Temple of the Dark Age - Cave'],
  diog: ['Something Cave - Cave'],
  marir: ['Something Cave - Cave'],
  searice: ['Mars - Cave'],
  kakuna: ['VIRIDIAN FOREST - LandNight'],
  metapod: ['VIRIDIAN FOREST - LandNight'],
  chingling: ['MT. MOON - Cave'],
  magikarp: ['Thermal Cavern - GoodRod'],
  abra: ['ROUTE 25 - LandNight'],
  cubaoop: ['Plastic World - GoodRod'],
  goopars: ['Mars - Cave'],
  bouldars: ['Mars Mine - Cave'],
  ligoop: ['Mars - Cave'],
  rocksmash: ['Trial Caverns - Water'],
  graveler: ['Trial Caverns - Water'],
  weepinbell: ['ROUTE 15 right - Land'],
  gloom: ['ROUTE 15 right - Land'],
  tentacruel: ['VERMILION CITY - GoodRod'],
  dugtrio: ['Ground World - Cave'],
  fearow: ['Route 23 down - Land'],
  pidgeotto: ['ROUTE 15 right - Land'],
  kingler: ['ROUTE 21 - GoodRod'],
  weezing: ['Flare Valley - Cave'],
  trinvasio: ['Mars - Cave'],
  drakosm: ['Fire World - Cave'],
  slowbro: ['Cerulean Cave 3 - Water'],
  golduck: ['Cerulean Cave 3 - Water'],
  jynx: ['Frost Valley - Cave'],
  venusaur: ['Venus - Cave'],
  blastoise: ["Bill's Garden - Land"],
  charizard: ["Bill's Garden - Land"],
  entei: ["Bill's Garden - Land"],
  raikou: ["Bill's Garden - Land"],
  suicune: ["Bill's Garden - Land"],
  articuno: ["Bill's Garden - Land"],
  zapdos: ["Bill's Garden - Land"],
  moltres: ["Bill's Garden - Land"],
  lugia: ["Bill's Garden - Land"],
  hooh: ["Bill's Garden - Land"],
  primeape: ['Shock Valley - Cave'],
  sandslash: ['VICTORY ROAD 3 - Cave'],
  arbok: ['Poison World - Cave'],
  machoke: ['Shock Valley - Cave'],
  marowak: ['VICTORY ROAD 3 - Cave'],
  nidorino: ['Safari Zone - Cave'],
  parasect: ['Mysterious Dungeon - Cave'],
  nidorina: ['Safari Zone - Cave'],
  seaking: ['Safari zone 4 - GoodRod'],
  venomoth: ['Safari zone 4 - Land'],
  wrufflet: ['Safari Zone - Cave'],
  dongorilla: ['Grass World - Land'],
  veloprey: ['Safari Zone - Cave'],
  rathy: ['Safari Zone - Cave'],
  cthoniurm: ['Ground World - Cave'],
  rinring: ['Burning Tower - Cave'],
  gohng: ['Burning Tower - Cave'],
  kirinriki: ['Burning Tower - Cave'],
  twinz: ['Burning Tower - Cave'],
  spidette: ['Route 1 BJ - Land'],
  sunmola: ['Burning Tower - Cave'],
  rayleep: ['Burning Tower - Cave'],
  blossomole: ['Burning Tower - Cave'],
  lefmew: ['Burning Tower - Cave'],
  tigrette: ['Burning Tower - Cave'],
  kurstraw: ['Burning Tower - Cave'],
  tael: ['Burning Tower - Cave'],
  bmurkrow: ['Burning Tower - Cave'],
  bomseel: ['Burning Tower - Cave'],
  wobbuffet: ['Mysterious Dungeon - Cave'],
  cocoobag: ['Beta Forest 2 - Land'],
  quailnote: ['Beta Forest - Land'],
  puppee: ['Beta Forest - Land'],
  snekindian: ['Beta Forest 2 - Land'],
  floxo: ['Beta Forest - Land'],
  pikachutwo: ['Mysterious Dungeon - Cave'],
  cbulbasaur: ['Mysterious Dungeon - Cave'],
  csquirtle: ['Mysterious Dungeon - Cave'],
  ccharmander: ['Mysterious Dungeon - Cave'],
  civysaur: ['Mysterious Dungeon - Cave'],
  cwartortle: ['Mysterious Dungeon - Cave'],
  ccharmeleon: ['Mysterious Dungeon - Cave'],
  trarsile: ['Poison World - Cave'],
  torturlens: ['Mars Mine - Cave'],
  marsybie: ['Mars Mine - Cave'],
  honarsal: ['Mars Mine - Cave'],
  araquanid: ['Trial Caverns - Water'],
  golisopod: ['Trial Caverns - GoodRod'],
  steenee: ['Trial Caverns - Cave'],
  mudsdale: ['Trial Caverns - Cave'],
  bewear: ['Fighting World - Cave'],
  maidcoresh: ['Mars Mine - Cave'],
  doveart: ['Venus - Cave'],
  hbuneary: ['Venus - Cave'],
  snakeart: ['Venus - Cave'],
  mfunown: ['Venus - Cave'],
  salember: ['Surface of the Sun - Cave'],
  solaress: ['Fire World - Cave'],
  suncrab: ['Magma World - Cave'],
  sanzucrow: ['Surface of the Sun - Cave'],
  pelipper: ['ROUTE 104 - Water'],
  mercary: ['Mercury - Cave'],
  tunacury: ['Mercury - Cave'],
  merqetal: ['Mercury - Cave'],
  charjabug: ['Temple of the Modern Age - Cave'],
  barbaracle: ['Thermal Cavern - Cave'],
  goodra: ['Dragon World - Cave'],
  clawitzer: ['Thermal Cavern - Water'],
  dragalge: ['Thermal Cavern - Water'],
  sularcl: ['Rock World - Cave'],
  cthuspawn: ['Outer Path - Cave'],
  deepone: ['Water World - Water'],
  sloggoth: ["R'lyeh - Cave"],
  acasmoc: ['Cosmic World - Cave'],
  splague: ['Cosmic World - Cave'],
  infinistake: ['Tech World - Cave'],
  ashgaaaaaa: ['Ghost World - Cave'],
  huntorror: ['Outer Outer Space - Cave'],
  flolyp: ['Outer Outer Space - Cave'],
  migus: ['Outer Outer Space - Cave'],
  searam: ['Outer Outer Space - Cave'],
  eldriz: ['Outer Path - Cave'],
  blasphlute: ['Outer Path - Cave'],
  darkyoun: ['Wood World - Land'],
  sloggeroth: ['Outer Path - Cave'],
  starpire: ['Cosmic World - Cave'],
  byaklight: ['Outer Path - Cave'],
  whaledriff: ['Water World - GoodRod'],
  drownskel: ['Water World - Water'],
  cradisk: ['Rock World - Cave'],
  crustolor: ['Water World - GoodRod'],
  tropilightning: ['Shock Valley - Cave'],
  miracact: ['Grass World - Land'],
  grasstacles: ['Grass World - Land'],
  melonvile: ['Grass World - Land'],
  gossifleur: ['Galar Cave - Cave'],
  cactoos: ['Beta Forest 2 - Land'],
  tikisque: ['Grass World - Land'],
  migoggoth: ['Cosmic World - Cave'],
  baumine: ['Virus World - Cave'],
  rapidash: ['Flare Valley - Cave'],
  darmanitan: ['Flare Valley - Cave'],
  heatmor: ['Flare Valley - Cave'],
  ajynx: ['Rock World - Cave'],
  sgraveler: ['Steam World - Land'],
  sgolem: ['Steam World - Land'],
  stweams: ['Steam World - Land'],
  atorkoal: ['Steam World - Land'],
  steamercom: ['Steam World - Land'],
  saplom: ['Ground World - Cave'],
  chestox: ['Wood World - Land'],
  capsileau: ['Wood World - Land'],
  rotree: ['Wood World - Land'],
  rookiedie: ['Galar Cave - Cave'],
  blipbug: ['Galar Cave - Cave'],
  yamper: ['Galar Cave - Cave'],
  nicket: ['Galar Cave - Cave'],
  wooloo: ['Galar Cave - Cave'],
  arrokuda: ['Galar Cave - Cave'],
  cramorant: ['Galar Cave - Cave'],
  eiscue: ['Galar Cave - Cave'],
  impidimp: ['Galar Cave - Cave'],
  rolycoly: ['Galar Cave - Cave'],
  chewtle: ['Galar Cave - Cave'],
  milcery: ['Galar Cave - Cave'],
  sinistea: ['Galar Cave - Cave'],
  hattena: ['Galar Cave - Cave'],
  sizzlipede: ['Galar Cave - Cave'],
  cufant: ['Galar Cave - Cave'],
  applin: ['Galar Cave - Cave'],
  toxel: ['Temple of the Modern Age - Cave'],
  snom: ['Galar Cave - Cave'],
  falinks: ['Galar Cave - Cave'],
  silicobra: ['Galar Cave - Cave'],
  morpeko: ['Galar Cave - Cave'],
  clobbopus: ['Galar Cave - Cave'],
  pincurchin: ['Galar Cave - Cave'],
  indeedee: ['Galar Cave - Cave'],
  gdarumaka: ['Galar Cave - Cave'],
  gfarfetchd: ['Galar Cave - Cave'],
  gstunfisk: ['Shock Valley - Cave'],
  gyamask: ['Galar Cave - Cave'],
  stonjourner: ['Sword and Shield Temple - Cave'],
  duraludon: ['Sword and Shield Temple - Cave'],
  dreepy: ['Hidden Path - Land'],
  dubwool: ['Sword and Shield Temple - Cave'],
  copperajah: ['Sword and Shield Temple - Cave'],
  coalossal: ['Sword and Shield Temple - Cave'],
  corviknight: ['Sword and Shield Temple - Cave'],
  drednaw: ['Sword and Shield Temple - Cave'],
  runerigus: ['Sword and Shield Temple - Cave'],
  grapidash: ['Sword and Shield Temple - Cave'],
  hatterene: ['Sword and Shield Temple - Cave'],
  grimmsnarl: ['Sword and Shield Temple - Cave'],
  drakloak: ['Sword and Shield Temple - Cave'],
  golem: ['Rock World - Cave'],
  gigalith: ['Rock World - Cave'],
  weepangel: ['Divine World - Cave'],
  rockodile: ['Rock World - Cave'],
  goatemon: ['Magic World - Cave'],
  alakazam: ['Magic World - Cave'],
  dtsareena: ['Magic World - Cave'],
  masigil: ['Magic World - Cave'],
  boxtress: ['Paper World - Cave'],
  robox: ['Tech World - Cave'],
  drawbie: ['Paper World - Cave'],
  cencyclodia: ['Paper World - Cave'],
  fissiom: ['Tech World - Cave'],
  radicrab: ['Nuclear World - Cave'],
  gammaray: ['Nuclear World - Cave'],
  reqimissile: ['Nuclear World - Cave'],
  godzillus: ['Nuclear World - Cave'],
  rodactyl: ['Nuclear World - Cave'],
  reactiox: ['Nuclear World - Cave'],
  nukadow: ['Nuclear World - Cave'],
  ndragonair: ['Nuclear World - Cave'],
  ndragonite: ['Nuclear World - Cave'],
  tortuagel: ['Divine World - Cave'],
  ryerpent: ['Divine World - Cave'],
  ledevilain: ['Chaos World - Cave'],
  helpme: ['Virus World - Cave'],
  catace: ['Chaos World - Cave'],
  chaosemple: ['Chaos World - Cave'],
  cryongi: ['Chaos World - Cave'],
  meatcko: ['Chaos World - GoodRod'],
  doomseye: ['Hidden Basement - Cave'],
  eldreye: ['Chaos World - Water'],
  augumon: ['Digiworld - Cave'],
  tsunomon: ['Digiworld - Cave'],
  motimon: ['Digiworld - Cave'],
  biyomon: ['Digiworld - Cave'],
  tentomon: ['Digiworld - Cave'],
  palmon: ['Digiworld - Cave'],
  penguinmon: ['Digiworld - Cave'],
  pagumon: ['Digiworld - Cave'],
  gomamon: ['Digiworld - Cave'],
  tokomon: ['Digiworld - Cave'],
  gabumon: ['Digiworld - Cave'],
  salamon: ['Digiworld - Cave'],
  tyrogue: ['Fighting World - Cave'],
  chokolit: ['Food World - Cave'],
  gurdurr: ['Fighting World - Cave'],
  mienshao: ['Shock Valley - Cave'],
  medicham: ['Frost Valley - Cave'],
  kapierce: ['Fighting World - Cave'],
  toneout: ['Fighting World - Cave'],
  luxray: ['Shock Valley - Cave'],
  glinoone: ['Flare Valley - Cave'],
  krookodile: ['Flare Valley - Cave'],
  gslowpoke: ['Frost Valley - Cave'],
  gmrmime: ['Frost Valley - Cave'],
  abomasnow: ['Frost Valley - Cave'],
  frosmoth: ['Frost Valley - Cave'],
  gdarmanitan: ['Frost Valley - Cave'],
  blizzlam: ['Frost Valley - Cave'],
  shelgon: ['Temple of the End Age - Cave'],
  gabite: ['Temple of the Shark Age - Cave'],
  anuzleaf: ['Wind World - Cave'],
  flyongolyp: ['Wind World - Cave'],
  muchoshot: ['Ground World - Cave'],
  voormisan: ['Voormithadreth - Cave'],
  seismitoad: ['Voormithadreth - Cave'],
  acolittle: ['Mount Voormithadreth - Land'],
  aculggua: ['Voormithadreth - Cave'],
  formspawn: ['Voormithadreth - Cave'],
  ariados: ['Voormithadreth - Cave'],
  enchip: ['Cyber World - Cave'],
  introll: ['Cyber World - Cave'],
  cypecker: ['Cyber World - Cave'],
  borygon2: ['Cyber World - Cave'],
  elinoone: ['Poison World - Cave'],
  serpeople: ['Poison World - Cave'],
  malevia: ['Poison World - Cave'],
  garbodor: ['Poison World - Cave'],
  elephyxiation: ['Poison World - Cave'],
  boomblix: ['Tech World - Cave'],
  ohmega: ['Beta Cave - Cave'],
  mt: ['Tech World - Cave'],
  statikman: ['Tech World - Cave'],
  smobill: ['Zombie World - Cave'],
  eboli: ['Virus World - Cave'],
  nexaphago: ['Virus World - Cave'],
  ebolette: ['Virus World - Cave'],
  drumgheist: ['Ghost World - Cave'],
  dusclops: ['Ghost World - Cave'],
  banette: ['Ghost World - Cave'],
  lynchost: ['Ghost World - Cave'],
  phantoy: ['Plastic World - Water'],
  lilskars: ['Ghost World - Cave'],
  coyotears: ['Ground World - Cave'],
  hippowdon: ['Ground World - Cave'],
  sandaconda: ['Ground World - Cave'],
  donphan: ['Ground World - Cave'],
  garchomp: ['Dragon World - Cave'],
  hundead: ['Zombie World - Cave'],
  zomboom: ['Zombie World - Cave'],
  zombeast: ['Zombie World - Cave'],
  wiondeath: ['Zombie World - Cave'],
  jackorse: ['Zombie World - Cave'],
  beaucake: ['Food World - Cave'],
  onigirice: ['Food World - Cave'],
  lunarat: ['Food World - Cave'],
  sashumish: ['Temple of the Shark Age - GoodRod'],
  pizzaurex: ['Food World - Cave'],
  alcremie: ['Food World - Cave'],
  cakeross: ['Food World - Cave'],
  curry: ['Food World - Cave'],
  beheeyem: ['Cosmic World - Cave'],
  ayymao: ['Cosmic World - Cave'],
  noivern: ['Dragon World - Cave'],
  slugeongoo: ['Dragon World - Cave'],
  dragapult: ['Dragon World - Cave'],
  maniquesque: ['Plastic World - GoodRod'],
  dolphottle: ['Plastic World - GoodRod'],
  ittybatty: ['Beta Cave - Cave'],
  gyao: ['Beta Cave - Cave'],
  gostee: ['Beta Cave - Cave'],
  echocho: ['Beta Cave - Cave'],
  dunspa: ['Beta Cave - Cave'],
  bashkull: ['Beta Cave - Cave'],
  wobslime: ['Beta Cave - Cave'],
  wobbo: ['Beta Cave - Cave'],
  eleko: ['Beta Cave - Cave'],
  buu: ['Beta Cave - Cave'],
  skelossil: ['Beta Cave - Cave'],
  cheepa: ['Beta Cave - GoodRod'],
  sumorog: ['Beta Cave - Water'],
  bwooper: ['Beta Cave - Water'],
  anvikin: ['Beta Cave - GoodRod'],
  keelisk: ['Beta Cave - Water'],
  flyfish: ['Beta Cave - GoodRod'],
  squi: ['Beta Cave - GoodRod'],
  qwilsmug: ['Beta Cave - GoodRod'],
  wadgon: ['Beta Cave - GoodRod'],
  beeta: ['Beta Cave - GoodRod'],
  ballbu: ['Beta Forest - Land'],
  boarstag: ['Beta Forest - Land'],
  balloom: ['Beta Forest - Land'],
  kachimatch: ['Beta Forest - Land'],
  koalma: ['Beta Forest - Land'],
  hippsycho: ['Beta Forest - Land'],
  lunabbit: ['Beta Forest - Land'],
  cherbim: ['Beta Forest 2 - Land'],
  kiteana: ['Beta Forest 2 - Land'],
  virualower: ['Beta Forest 2 - Land'],
  misfly: ['Beta Forest 2 - Land'],
  beetul: ['Beta Forest 2 - Land'],
  stingscorp: ['Beta Forest 2 - Land'],
  bhoothoot: ['Beta Forest 2 - Land'],
  keewee: ['Beta Forest 2 - Land'],
  sneewii: ['Beta Forest 2 - Land'],
  blissey: ['The Dungeon - Cave'],
  zombicater: ['Snakewoods - Land'],
  decarill: ['Snakewoods - Land'],
  brimshrew: ['Snakewoods - Land'],
  houndsour: ['Snakewoods - Land'],
  clegoyle: ['Snakewoods - Land'],
  miaby: ['Snakewoods - Land'],
  elecharge: ['Snakewoods - Land'],
  skinskin: ['Snakewoods - Land'],
  irivatar: ['Snakewoods - Land'],
  snkgrimreaper: ['Snakewoods - Land'],
  yeutdoom: ['Snakewoods - Land'],
  rustum: ['Snakewoods - Land'],
  moulder: ['Snakewoods - Water'],
  roteen: ['Snakewoods - GoodRod'],
  polihag: ['Snakewoods - OldRod'],
  sevicious: ['Snakewoods - Water'],
  evidisc: ['Snakewoods - GoodRod'],
  telson: ['Snakewoods - GoodRod'],
  blackuto: ['Snakewoods - GoodRod'],
  qwilshark: ['Snakewoods - GoodRod'],
  annesque: ['Anne World - Cave'],
  scrunrafe: ['Anne World - Cave'],
  coneanne: ['Anne World - Cave'],
  loganne: ['Anne World - Cave'],
  anneoo: ['Anne World - Cave'],
  voidanne: ['Anne World - Cave'],
  emptyanne: ['Anne World - Cave'],
  jaggu: ['Temple of the Shark Age - GoodRod'],
  wexeggcute: ['Temple of the Extinction Age - Cave'],
  mukma: ['Temple of the Extinction Age - Cave'],
  syclar: ['Endless - Cave'],
  embirch: ['Endless - Cave'],
  breezi: ['Endless - Cave'],
  rebble: ['Endless - Cave'],
  privatyke: ['Endless - Cave'],
  smvoodoll: ['Endless - Cave'],
  scratchet: ['Endless - Cave'],
  necturine: ['Endless - Cave'],
  cupra: ['Endless - Cave'],
  brattler: ['Endless - Cave'],
  phallusaur: ['Endless - Cave'],
  flamoozer: ['Endless - Cave'],
  snugglow: ['Endless Floor 2 - Cave'],
  floatoy: ['Endless Floor 2 - Cave'],
  pluffle: ['Endless Floor 2 - Cave'],
  mumbao: ['Endless Floor 2 - Cave'],
  fawnifer: ['Endless Floor 2 - Cave'],
  smogecko: ['Endless Floor 2 - Cave'],
  swirlpool: ['Endless Floor 2 - Cave'],
  cawdet: ['Endless Floor 2 - Cave'],
  volkritter: ['Endless Floor 2 - Cave'],
  cspoink: ['Endless Floor 2 - Cave'],
  mspain: ['Endless Floor 2 - Cave'],
  assdeer: ['Endless Floor 2 - Cave'],
  hucaterpie: ['Pokegirl Island - Land'],
  hupidgey: ['Pokegirl Island - Land'],
  hurattata: ['Pokegirl Island - Land'],
  huweedle: ['Pokegirl Island - Land'],
  huspearow: ['Pokegirl Island - Land'],
  husandshrew: ['Pokegirl Island - Land'],
  huekans: ['Pokegirl Island - Land'],
  huoddish: ['Pokegirl Island - Land'],
  hupikachu: ['Pokegirl Island - Land'],
  hunidoranfe: ['Pokegirl Island - Land'],
  hunidoranma: ['Pokegirl Island - Land'],
  huvulpix: ['Pokegirl Island - Land'],
  hupsyduck: ['Pokegirl Island - Water'],
  hupoliwag: ['Pokegirl Island - Water'],
  hutentacool: ['Pokegirl Island - Water'],
  huslowpoke: ['Pokegirl Island - Water'],
  hustaryu: ['Pokegirl Island - Water'],
  humagikarp: ['Pokegirl Island - OldRod'],
  hugoldeen: ['Pokegirl Island - OldRod'],
  huhorsea: ['Pokegirl Island - GoodRod'],
  hushellder: ['Pokegirl Island - GoodRod'],
  hugrimer: ['Pokegirl Island - GoodRod'],
  hukrabby: ['Pokegirl Island - GoodRod'],
  huomanyte: ['Pokegirl Island - GoodRod'],
  hukabuto: ['Pokegirl Island - GoodRod'],
  hudratini: ['Pokegirl Island - GoodRod'],
  huzubat: ['Pokegirl Cave - Cave'],
  hugeodude: ['Pokegirl Cave - Cave'],
  hudiglett: ['Pokegirl Cave - Cave'],
  huparas: ['Pokegirl Cave - Cave'],
  huexeggcute: ['Pokegirl Cave - Cave'],
  hukoffing: ['Pokegirl Cave - Cave'],
  humankey: ['Pokegirl Cave - Cave'],
  hugrowlithe: ['Pokegirl Cave - Cave'],
  humachop: ['Pokegirl Cave - Cave'],
  huabra: ['Pokegirl Cave - Cave'],
  hupinsir: ['Pokegirl Cave - Cave'],
  huscyther: ['Pokegirl Cave - Cave'],
  huvenonat: ['Pokegirl Cave 2 - Cave'],
  humagnemite: ['Pokegirl Cave 2 - Cave'],
  huponyta: ['Pokegirl Cave 2 - Cave'],
  hubellsprout: ['Pokegirl Cave 2 - Cave'],
  hutangela: ['Pokegirl Cave 2 - Cave'],
  hudrowzee: ['Pokegirl Cave 2 - Cave'],
  huonix: ['Pokegirl Cave 2 - Cave'],
  hujynx: ['Pokegirl Cave 2 - Cave'],
  humagmar: ['Pokegirl Cave 2 - Cave'],
  huelectabuzz: ['Pokegirl Cave 2 - Cave'],
  hugastly: ['Pokegirl Cave 2 - Cave'],
  humrmime: ['Pokegirl Cave 2 - Cave'],
  blanda: ['Brokenace255 - Cave'],
  moustab: ['Brokenace255 - Cave'],
  frospidey: ['Brokenace255 - Cave'],
  hillarge: ['Brokenace255 - Cave'],
  beanoy: ['Brokenace255 - Cave'],
  boebii: ['Brokenace255 - Cave'],
  molstub: ['Brokenace255 - Cave'],
  alcohog: ['Brokenace255 - Cave'],
  huranium: ['Brokenace255 - Cave'],
  trollel: ['Brokenace255 - Cave'],
  loleye: ['Brokenace255 - Cave'],
  trumporn: ['Brokenace255 - Cave'],
  wetloon: ['Brokenace255 - Water'],
  ploop: ['Brokenace255 - Water'],
  salsik: ['Brokenace255 - GoodRod'],
  capseal: ['Brokenace255 - Water'],
  cartcap: ['Brokenace255 - Water'],
  yellynth: ['Brokenace255 - GoodRod'],
  tinna: ['Brokenace255 - GoodRod'],
  eaglass: ['Brokenace255 - GoodRod'],
  sodrade: ['Brokenace255 - GoodRod'],
  gruppy: ['Brokenace255 - Cave'],
  sparroof: ['Brokenace255 - Cave'],
  gullbage: ['Brokenace255 - Cave'],
  twiggerd: ['Brokenace255 - Cave'],
  pinnint: ['Brokenace255 - Cave'],
  schnozard: ['Brokenace255 - Cave'],
  pantom: ['Brokenace255 - Cave'],
  slugar: ['Brokenace255 - Cave'],
  pictoji: ['Brokenace255 - Cave'],
  nyuvel: ['Brokenace255 - Cave'],
  pizzauro: ['Brokenace255 - Cave'],
  spovum: ['Brokenace255 - Cave'],
  squbble: ['Brokenace255 - Water'],
  snotto: ['Brokenace255 - Water'],
  pengwarn: ['Brokenace255 - Water'],
  marmin: ['Brokenace255 - Water'],
  clownim: ['Brokenace255 - GoodRod'],
  clagma: ['Brokenace255 - GoodRod'],
  tabbee: ['Brokenace255 - GoodRod'],
  trichic: ['Brokenace255 - GoodRod'],
  hairjog: ['Brokenace255 - Cave'],
  teevz: ['Brokenace255 - Cave'],
  tardough: ['Brokenace255 - Cave'],
  splug: ['Brokenace255 - Cave'],
  senteddi: ['Brokenace255 - Cave'],
  pinana: ['Brokenace255 - Cave'],
  cuffy: ['Brokenace255 - Cave'],
  oymayt: ['Brokenace255 - Cave'],
  flopple: ['Brokenace255 - Cave'],
  fleap: ['Brokenace255 - Cave'],
  shlario: ['Brokenace255 - Cave'],
  ovilock: ['Brokenace255 - Cave'],
  goomly: ['Mushroom Kingdom - LandNight'],
  koopatroopa: ['Mushroom Kingdom - LandNight'],
  shyguy: ['Mushroom Kingdom - LandNight'],
  bobomb: ['Mushroom Kingdom - LandNight'],
  mtoad: ['Mushroom Kingdom - LandDay'],
  toadette: ['Mushroom Kingdom - LandDay'],
  koopaparatroopa: ['Mushroom Kingdom - LandDay'],
  thwompo: ['Mushroom Kingdom - LandNight'],
  doomimp: ['DOOT - Cave'],
  doompinky: ['DOOT - Cave'],
  dlostsoul: ['DOOT - Cave'],
  mancubus: ['DOOT - Cave'],
  doomhellknight: ['DOOT - Cave'],
  cacemon: ['DOOT - Cave'],
  doomrevenant: ['DOOT - Cave'],
  darchvile: ['DOOT - Cave'],
  painelemental: ['DOOT - Cave'],
  sawcubus: ['DOOT - Cave'],
  arachnotron: ['DOOT - Cave'],
  dwatcher: ['DOOT - Cave'],
  bastiodon: ['Hidden Path - Land'],
  thorita: ['Hidden Path - Land'],
  tyrantrum: ['Hidden Path - Land'],
  rampardos: ['Hidden Path - Land'],
  meganium: ['Hidden Path - Land'],
  crewmongus: ['Sussy Forest - LandNight'],
  crwutemate: ['Sussy Forest - LandNight'],
  bibarel: ['Hidden Research Area - Land'],
  chargradon: ['Hidden Research Area - Land'],
  burnasaur: ['Hidden Research Area - Land'],
  btorterra: ['Hidden Research Area - Land'],
  gtropius: ['Hidden Research Area - Land'],
  furror: ['Hidden Research Area - Land'],
  bgarchomp: ['Hidden Research Area - Land'],
  finish: ['Hidden Research Area - Water'],
  fishember: ['Hidden Research Area - Water'],
  squinky: ['Hidden Research Area - Water'],
  jawetech: ['Hidden Research Area - Water'],
  tmagnemite: ['Lab - Cave'],
  lurquad: ['Lab - Cave'],
  arachoe: ['Lab - Cave'],
  rpgidget: ['Lab - Cave'],
  rprazor: ['Lab - Cave'],
  rprocker: ['Lab - Cave'],
  calculus: ['Lab - Cave'],
  nitorech: ['Lab - Cave'],
  pumpird: ['Lab BF1 - Cave'],
  rpboomer: ['Lab BF1 - Cave'],
  rpmolbot: ['Lab BF1 - Cave'],
  supaninteno: ['Lab BF1 - Cave'],
  sewan: ['Lab BF1 - Cave'],
  traino: ['Lab BF1 - Cave'],
  rpmedbot: ['Lab BF1 - Cave'],
  emerl: ['Lab BF1 - Cave'],
  balistagon: ['Lab BF1 - Cave'],
  rpsunny: ['Lab BF1 - Cave'],
  mechans: ['Lab BF2 - Cave'],
  bitsy: ['Lab BF2 - Cave'],
  toater: ['Lab BF2 - Cave'],
  lagannech: ['Lab BF2 - Cave'],
  rpramjet: ['Lab BF2 - Cave'],
  chibirobo: ['Lab BF2 - Cave'],
  fukoujo: ['Lab BF2 - Cave'],
  ptero: ['Wackissic Park - Land'],
  trex: ['Wackissic Park - Land'],
  trice: ['Wackissic Park - Land'],
  ovi: ['Wackissic Park - Land'],
  brachio: ['Wackissic Park - Land'],
  paeria: ['Wackissic Park - Land'],
  ankylo: ['Wackissic Park - Land'],
  dimorph: ['Wackissic Park - Land'],
  dimetrodon: ['Wackissic Park - Land'],
  stego: ['Wackissic Park - Land'],
  iguano: ['Wackissic Park - Land'],
  lystro: ['Wackissic Park - Land'],
  veloci: ['Wackissic Park - LandNight'],
  composo: ['Wackissic Park - LandNight'],
  plateo: ['Wackissic Park - LandNight'],
  rodent: ['Wackissic Park - LandNight'],
  pachy: ['Wackissic Park - LandNight'],
  diplodocus: ['Wackissic Park - LandNight'],
  therizan: ['Wackissic Park - LandNight'],
  carnotaurus: ['Wackissic Park - LandNight'],
  lagosu: ['Wackissic Park - LandNight'],
  siamo: ['Wackissic Park - LandNight'],
  eoraptor: ['Wackissic Park - LandNight'],
  longis: ['Wackissic Park - LandNight'],
  struthio: ['Wackissic Park - Water'],
  dragonfly: ['Wackissic Park - Water'],
  amarga: ['Wackissic Park - Water'],
  arche: ['Wackissic Park - Water'],
  quetzal: ['Wackissic Park - Water'],
  suchomi: ['Wackissic Park - GoodRod'],
  para: ['Wackissic Park - GoodRod'],
  krono: ['Wackissic Park - GoodRod'],
  plesio: ['Wackissic Park - GoodRod'],
  ichthyo: ['Wackissic Park - GoodRod'],
  progano: ['Wackissic Park - GoodRod'],
  ammonite: ['Wackissic Park - GoodRod'],
  deinosuchus: ['Wackissic Park - GoodRod'],
  aeromadio: ['Madio Cave - Cave'],
  bonemadio: ['Madio Cave - Cave'],
  treemadio: ['Madio Cave - Cave'],
  solmadio: ['Madio Cave - Cave'],
  healmadio: ['Madio Cave - Cave'],
  zapmadio: ['Madio Cave - Cave'],
  shademadio: ['Madio Cave - Cave'],
  normadio: ['Madio Cave - Cave'],
  gluemadio: ['Madio Cave - Cave'],
  earthmadio: ['Madio Cave - Cave'],
  burstmadio: ['Madio Cave - Cave'],
  bugmadio: ['Madio Cave - Cave'],
  seamadio: ['Madio Cave - Water'],
  mistmadio: ['Madio Cave - Water'],
  oilmadio: ['Madio Cave - Water'],
  frostymadio: ['Madio Cave - Water'],
  pongmadio: ['Madio Cave - Water'],
  glute: ['Deep Snakewoods - Land'],
  impychu: ['Deep Snakewoods - Land'],
  kenchira: ['Deep Snakewoods - Land'],
  devilchu: ['Deep Snakewoods - Land'],
  cinderco: ['Deep Snakewoods - Land'],
  walts: ['Deep Snakewoods - Land'],
  commanossy: ['Deep Snakewoods - Land'],
  tricko: ['Deep Snakewoods - Land'],
  franichic: ['Deep Snakewoods - Land'],
  gigawolf: ['Deep Snakewoods - Land'],
  smoquill: ['Deep Snakewoods - Water'],
  fangkip: ['Deep Snakewoods - Water'],
  blinodile: ['Deep Snakewoods - Water'],
  hubrimshrew: ['Snakewood Girl Island BF1 - Cave'],
  hunidoblood: ['Snakewood Girl Island BF1 - Cave'],
  humetalran: ['Snakewood Girl Island BF1 - Cave'],
  huclegoyle: ['Snakewood Girl Island BF1 - Cave'],
  humoulder: ['Snakewood Girl Island BF1 - Cave'],
  husnkgrimreaper: ['Snakewood Girl Island BF1 - Cave'],
  huboilbasaur: ['Snakewood Girl Island - Land'],
  hurotmander: ['Snakewood Girl Island - Land'],
  huoozle: ['Snakewood Girl Island - Land'],
  huslasherpie: ['Snakewood Girl Island - Land'],
  huintestinela: ['Snakewood Girl Island - Land'],
  huzombicater: ['Snakewood Girl Island - Land'],
  hupolihag: ['Snakewood Girl Depths - Cave'],
  huroteen: ['Snakewood Girl Depths - Cave'],
  hublackuto: ['Snakewood Girl Depths - Cave'],
  hustarruz: ['Snakewood Girl Depths - Cave'],
  dementad: ['Snakewood Girl Depths - Cave'],
  leviuto: ['Snakewood Girl Depths - Cave'],
  napseel: ['Snakewood Girl Depths - Cave'],
  sleamy: ['Snakewood Girl Depths - Cave'],
  dgyarados: ['Snakewood Girl Depths - Cave'],
  hustabra: ['Snakewood Girl Island BF2 - Cave'],
  huhombone: ['Snakewood Girl Island BF2 - Cave'],
  hudevilchu: ['Snakewood Girl Island BF2 - Cave'],
  husnkeyeeye: ['Snakewood Girl Island BF2 - Cave'],
  huelectabugs: ['Snakewood Girl Island BF2 - Cave'],
  humiasmar: ['Snakewood Girl Island BF2 - Cave'],
  huslimex: ['Snakewood Girl Island BF2 - Cave'],
  hugorelax: ['Snakewood Girl Island BF2 - Cave'],
  huglitchlett: ['Snakewood Girl Island BF2 - Cave'],
  hutoxitung: ['Snakewood Girl Island BF2 - Cave'],
  hudevilmar: ['Snakewood Girl Island BF2 - Cave'],
  huskylax: ['Snakewood Girl Island BF2 - Cave'],
};
