export const FAMILY_POKEMON: {[key: string]: string[]} = {
  colosshale: ['colossoil'],
  scratchet: ['tomohawk'],
  cupra: ['argalis', 'aurumoth'],
  necturine: ['necturna'],
  brattler: ['malaconda'],
  cawdet: ['cawmodore'],
  biyomon: ['birdramon', 'garudamon', 'hououmon', 'varodurumon'],
  troch: ['floller'],
  tsunomon: [
    'gabumon',
    'elecmon',
    'garurumon',
    'weregarurumon',
    'metalgarurumon',
    'bmetalgarurumon',
    'zeedgarurumon',
    'omegamon',
    'leomon',
    'grapleomon',
    'saberleomon',
    'bancholeomon',
  ],
  motimon: [
    'tentomon',
    'dokunemon',
    'kabuterimon',
    'rmegakabuterimon',
    'bmegakabuterimon',
    'herculeskabuterimon',
    'tyrantkabuterimon',
    'dokugumon',
    'arukenimon',
    'parasimon',
  ],
  napseel: ['bomseel', 'frostiseel', 'shockaseel', 'necroseel', 'gloseel'],
  palmon: ['togemon', 'lilymon', 'ponchomon', 'rosemon', 'babamon'],
  volkritter: ['volkraken'],
  snugglow: ['plasmanta'],
  lurquad: ['disfunbot', 'sheridryoid', 'kizzeep', 'noofr'],
  gdiglett: ['gdugtrio'],
  cnosepass: ['cprobopass'],
  penguinmon: ['dolphmon', 'whamon', 'neptunemon', 'marineangemon'],
  rprocker: ['rprockerz'],
  rprazor: ['rprazorz', 'rpboba'],
  rpsunny: ['rpsun02', 'rpsuncust'],
  rpmedbot: ['rpmeddy', 'rpdocbot', 'rpmeddyz'],
  wtrubbish: ['wgarbodor', 'cottandy'],
  wgulpin: ['wswalot', 'swallice'],
  wapplin: ['wflapple', 'wappletun'],
  dinofur: ['furrygon', 'furror'],
  whattena: ['whattrem', 'whatterene'],
  wgothita: ['sailorita', 'admirelle'],
  paintgon: ['acrylomodo'],
  rattastic: ['edgucate'],
  passta: ['sspaghetti'],
  barkbark: ['timbark'],
  floatskull: ['bloodetan', 'bloodoom'],
  porkopter: ['bacopter'],
  eggy: ['eggception'],
  panslash: ['simislash'],
  loccoon: ['buzzerk'],
  pillost: ['shrieet', 'duvetious'],
  rpmolbot: ['rpdigger'],
  wnosepass: ['wprobopass'],
  wexeggcute: ['wexeggutor'],
  wkoffing: ['wweezing', 'gweezing'],
  rpboomer: ['rpairraid', 'rpboomb1'],
  rpgidget: ['rpbetty', 'rpbettyz', 'rpgranny'],
  kubfu: ['ssurshifu', 'rsurshifu'],
  gslowpoke: ['gslowbro', 'gslowking'],
  tsunonasu: ['gilerth', 'gilgierth', 'gigagigerth'],
  bdrifloon: ['bdrifblim'],
  ivenonat: ['ivenomoth'],
  adrowzee: ['ahypno'],
  curry: [
    'mcurry',
    'richmcurry',
    'juicymcurry',
    'cheesemcurry',
    'breadmcurry',
    'pastamcurry',
    'cocomcurry',
    'leekmcurry',
    'samcurry',
    'mumcurry',
    'pacmcurry',
    'appmcurry',
    'beamcurry',
    'burmcurry',
    'tropmcurry',
    'frymcurry',
    'crmmcurry',
    'rammcurry',
    'seamcurry',
    'salmcurry',
    'slomcurry',
    'bonmcurry',
    'herbmcurry',
    'eggmcurry',
    'potmcurry',
    'bcurry',
    'sabcurry',
    'mumbcurry',
    'pacbcurry',
    'appbcurry',
    'beabcurry',
    'burbcurry',
    'tropbcurry',
    'frybcurry',
    'crmbcurry',
    'rambcurry',
    'seabcurry',
    'salbcurry',
    'slobcurry',
    'bonbcurry',
    'eggbcurry',
    'potbcurry',
    'herbbcurry',
    'cocobcurry',
    'breadbcurry',
    'pastabcurry',
    'cheesebcurry',
    'juicybcurry',
    'richbcurry',
  ],
  barkhol: ['octopine'],
  yummydew: ['sucklaxis', 'honbrosia'],
  pawnembra: ['dusklaw'],
  froglide: ['amphibifloat'],
  gomamon: ['ikkakumon', 'zudomon', 'vikemon'],
  wbarboach: ['wwhiscash'],
  tokomon: ['patamon', 'angemon', 'magnaangemon', 'seraphimon'],
  salamon: [
    'tailmon',
    'mikemon',
    'angewomon',
    'ophanimon',
    'holydramon',
    'bastemon',
    'lilithmon',
  ],
  ccleffa: ['cclefairy', 'cclefable'],
  doratgon: ['kingdorah'],
  pagumon: [
    'goblimon',
    'blackagumon',
    'snowgoblimon',
    'shamanmon',
    'demidevimon',
    'ogremon',
    'fugamon',
    'hyogamon',
    'digitamamon',
    'fdigitamamon',
    'titamon',
    'minervamon',
    'devitamamon',
    'belphemon',
    'mervamon',
    'vgreymon',
    'devimon',
    'myotismon',
    'vnmyotismon',
    'mmyotismon',
    'barbamon',
    'piedmon',
  ],
  relemon: ['viximon', 'renamon', 'kyubimon', 'taomon', 'sakuyamon'],
  wpachirisu: ['mkachirisu', 'fkachirisu'],
  dfpsyduck: ['dfgolduck'],
  gordrarm: ['garagonarm'],
  acolittle: [
    'glaakultist',
    'acthulist',
    'acolthep',
    'acosoth',
    'acultgoat',
    'aculggua',
    'aculyig',
    'acultchotcho',
    'aculthqua',
    'aculyellow',
    'aculzoth',
    'aculthuga',
  ],
  teaplasm: ['sinistea', 'polteageist'],
  tfkochia: ['tfraygirth', 'tfraygoten'],
  dratyke: ['drampa', 'mdrampa'],
  dsnorunt: ['dglalie', 'dfroslass'],
  dpsyduck: ['dgolduck'],
  lobotite: ['lobotitan', 'lobautomous'],
  steamling: ['steamingo'],
  burniel: ['zophlare'],
  dralts: ['dkirlia', 'dgardevoir', 'dgallade'],
  blat: ['coronablat', 'batood', 'blatsoup'],
  whoppip: ['wskiploom', 'wjumpluff'],
  houraioll: ['goliatholl'],
  crikatank: ['rikatank'],
  cmaribel: ['thmaribel'],
  crenko: ['threnko'],
  monkid: [
    'floweyrst',
    'asrielgot',
    'asrieldrem',
    'undyrate',
    'papyrousle',
    'asgoat',
    'toriegoat',
    'mettabot',
    'floweyr',
    'characide',
  ],
  dwelder: ['weldigger'],
  ngrimer: ['nmuk'],
  tmagnemite: ['tmagneton', 'magnezone', 'kaijumagnezone'],
  bjigglypuff: ['bwigglytuff', 'spooklypuff'],
  fhorsea: ['fseadra', 'fkingdra'],
  beholdie: ['beholdeye', 'teyerant'],
  chespin: ['cheslios', 'quilladin', 'solahog', 'chesnaught', 'kaijuquilladin'],
  fennekin: [
    'omephox',
    'braixen',
    'neofen',
    'hufennekin',
    'delphox',
    'hubraixen',
    'hudelphox',
  ],
  froakie: ['neoille', 'frogadier', 'simprog', 'greninja'],
  pumpird: ['pumpjackird'],
  gigimon: [
    'guilmon',
    'growlmon',
    'wargrowlmon',
    'gallantmon',
    'megidramon',
    'darkdramon',
    'chaosmon',
  ],
  larvipede: ['sandrawler', 'kaijusandrawler'],
  gummymon: ['terriermon', 'gargomon', 'rapidmon', 'megagargomon'],
  chuumon: ['sukamon'],
  numemon: [
    'karatsukinumemon',
    'numemonx',
    'platinumsukamon',
    'etemon',
    'metaletemon',
    'kingetemon',
  ],
  otamamon: ['monzaemon', 'gekomon', 'geremon', 'shogungekomon', 'pukumon'],
  koromon: [
    'seadramon',
    'snowagumon',
    'augumon',
    'megaseadramon',
    'metalseadramon',
    'leviamon',
  ],
  augumon: [
    'metalgreymonv',
    'greymon',
    'tyrannomon',
    'toyagumon',
    'stoyagumon',
    'hitleragumon',
    'metalgreymon',
    'skullgreymon',
    'wargreymon',
    'wargreymonv',
    'victorygreymon',
    'machinedramon',
    'mastertyrannomon',
    'samudramon',
  ],
  nanimon: ['bombernanimon'],
  snuggice: ['sweateryeti'],
  piplup: [
    'primpendlup',
    'prinplup',
    'primplup',
    'bprinplup',
    'empoleon',
    'bempoleon',
  ],
  grotlefake: ['faketerra'],
  thoothoot: ['tnoctowl'],
  mercary: ['merqetal'],
  matzio: ['matzahz'],
  jgolett: ['jgolurk'],
  wrufflet: ['wbraviary'],
  minccino: ['kaijucinccino', 'cinccino', 'kaijuminccino'],
  corida: ['kungfloo', 'yanenvy'],
  timbito: ['doughnutter', 'sufdonyut'],
  bulbasaur: ['ivysaur', 'venusaur', 'bvenusaur', 'kaijuvenusaur'],
  charmander: ['charmeleon', 'charizard', 'charizardo', 'skyrimzard'],
  squirtle: ['wartortle', 'blastyke', 'blastoise', 'wartoise'],
  caterpie: ['metapod', 'rayquaza', 'butterfree', 'firefree'],
  weedle: ['kakuna', 'beedrill'],
  pidgey: ['pidgeotto', 'pidgeot'],
  rattata: [
    'raticate',
    'praticate',
    'raticlaw',
    'birthdayraticate',
    'praticlaw',
  ],
  spearow: ['fearow', 'bspearow', 'aves'],
  spearolt: ['mfearow', 'kaijufearow', 'fearolt'],
  ekans: ['arbok'],
  huekans: ['marbok', 'huarbok'],
  pikachu: [
    'raichu',
    'araichu',
    'pikared',
    'pikabud',
    'gorochu',
    'mpikachu',
    'gpikachu',
    'spongechu',
  ],
  sandshrew: ['sandslash'],
  nidoranfe: ['nidorina', 'nidoqueen'],
  nidoranma: ['nidorino', 'nidoking'],
  clefairy: ['clefable', 'bclefairy', 'clefmontop'],
  vulpix: ['ninetales'],
  huvulpix: ['mninetales', 'huninetales'],
  jigglypuff: ['wigglytuff', 'trigglytuff'],
  zubat: ['golbat', 'crobat'],
  oddish: [
    'gloom',
    'potish',
    'vileplume',
    'bellossom',
    'bbellossom',
    'trickish',
  ],
  paras: ['parasect'],
  dvenonat: ['venomoth', 'manomoth'],
  venonat: ['venomothra'],
  diglett: ['dugtrio'],
  nimbett: ['subroclock', 'stratrio'],
  meowth: ['persian', 'feliflame', 'gmeowth', 'kperrserker', 'mpersian'],
  psyduck: ['golduck', 'golpsyduck'],
  mankey: ['primeape'],
  growlithe: ['arcanine'],
  iolithe: ['marcanine', 'ionnine'],
  poliwag: [
    'poliwhirl',
    'bpoliwag',
    'poliwrath',
    'politoed',
    'bpolitoed',
    'nyosuka',
  ],
  abra: ['kadabra', 'alakazam', 'alenkar'],
  machop: ['machoke', 'kaijumachop', 'machamp', 'kaijumachoke'],
  bellsprout: [
    'weepinbell',
    'sbellsprout',
    'weepinbarf',
    'bellscrop',
    'victreebel',
    'belmitt',
    'atlasbell',
  ],
  tentacool: ['tentacruel'],
  geodude: ['graveler', 'wdgolem', 'golem'],
  huponyta: ['rapidash'],
  ponyta: ['pegazeus', 'mrapidash', 'xmrapidash'],
  slowpoke: ['slowbro', 'slowking', 'slowloss', 'clowdpoke', 'mslowbro'],
  magnemite: ['magneton'],
  farfetchd: ['madame', 'flamefetchd', 'nfarfetchd'],
  doduo: ['dodrio'],
  seel: ['dewgong', 'bseel', 'narwhar'],
  grimer: ['muk'],
  shellder: ['cloyster', 'shelldor', 'turbann'],
  gastly: ['haunter', 'gengar', 'gogengar', 'frozone', 'hellraiser'],
  hugastly: ['kaijugastly', 'huhaunter', 'hugengar'],
  hyonix: ['steelix', 'malicix'],
  drowzee: ['hypno', 'dreamaster', 'kaijuhypno'],
  krabby: ['kingler', 'kaijukrabby', 'ancienkrab', 'gkingler', 'kaijukingler'],
  voltorb: ['electrode', 'voltcube', 'dampelectrode'],
  huvoltorb: ['alactrode', 'melectrode', 'huelectrode'],
  exeggcute: ['exeggutor', 'aexeggutor'],
  cubone: ['marowak', 'amarowak', 'matriawak', 'fracture'],
  lickitung: ['lickilicky', 'likk', 'luigi', 'hulickitung'],
  koffing: ['weezing'],
  rhyhorn: ['rhydon'],
  hurhyhorn: ['rhyperior', 'gyarth', 'hurhydon'],
  chansey: [
    'bblissey',
    'happi',
    'clegnyana',
    'gamble',
    'chanseychanse',
    'commanossy',
    'blissey',
  ],
  tangela: ['tangrowth', 'gelanla'],
  horsea: ['seadra', 'kingdra', 'bkingdra', 'bkingdratwo', 'unfinkingdra'],
  goldeen: ['seaking'],
  staryu: ['starmie', 'starwi', 'starmish', 'starruz'],
  scyther: ['scizor', 'scizors', 'icepick', 'scytheper', 'mscizor'],
  hujynx: ['mjynx'],
  electabuzz: ['electivire'],
  humagmar: ['magmortar'],
  pinsir: ['pinswing', 'pinsire', 'plux'],
  magikarp: ['gyarados', 'wyrmados', 'gyaradeth', 'mgyarados'],
  lapras: ['laprageddon', 'laprince', 'betalapras'],
  ditto: ['amorphitto', 'animon', 'kaijuditto'],
  eevee: [
    'lonliness',
    'komodeon',
    'veneon',
    'ailmeon',
    'shadeon',
    'scorpeon',
    'arteon',
    'slickeon',
    'eeveeon',
    'crysteon',
    'memeon',
    'temporeon',
    'eldreon',
    'phlebeon',
    'divineon',
    'snktoxeon',
    'snkdemoneon',
    'affecteon',
    'cakeon',
    'plusheon',
    'transpareon',
    'artificeon',
    'gadgeteon',
    'tornadeon',
    'frequenceon',
    'pageon',
    'geevee',
    'rotteon',
    'plutoneon',
    'timberreon',
    'volcaneon',
    'condenseon',
    'vaporeon',
    'jolteon',
    'flareon',
    'leafeon',
    'glaceon',
    'espeon',
    'umbreon',
    'sylveon',
    'arcaneon',
    'spaceon',
    'solareon',
    'terreon',
    'stoneon',
    'metaleon',
    'phobeon',
    'gooseon',
    'virtualeon',
    'zephyreon',
    'champeon',
    'phanteon',
    'aumbreon',
    'ballooneon',
    'eeeee',
    'bespeon',
    'kaijuumbreon',
    'leafeo',
  ],
  porygon: [
    'porygon2',
    'poryrus',
    'borygon2',
    'dlcorygon',
    'kaijuporygon',
    'hammerygon',
    'swordygon',
    'shieldygon',
    'porygonz',
    'poryrusz',
  ],
  omanyte: ['omastar'],
  huomanyte: ['momastar', 'huomastar'],
  kabuto: ['kabutops', 'kaijukabuto', 'mkabutops'],
  aerodactyl: ['aerodactold'],
  dratini: ['dragonair', 'bdragonair', 'yoshi', 'dragonite'],
  chikorita: ['bayleef', 'meganium'],
  cyndaquil: ['quilava', 'bcyndaquil', 'acyndaquil', 'typhlosion'],
  totodile: ['croconaw', 'btotodile', 'feraligatr'],
  sentret: ['furret', 'wfurret', 'bsentret', 'bfurret'],
  hoothoot: ['noctowl', 'bhoothoot', 'hoohoo'],
  ledyba: ['ledian', 'tripstar'],
  spinarak: ['ariados', 'smariados', 'mariados', 'bariados'],
  chinchou: ['lanturn', 'bchinchou', 'blanturn'],
  pichu: ['apichu', 'bpichu', 'pikachu'],
  acleffa: ['clefairy'],
  aigglybuff: ['jigglypuff'],
  igglybuff: ['qigglybuff'],
  togepi: ['togetic', 'togekiss', 'btogekiss'],
  natu: ['xatu', 'kaijunatu', 'zatu'],
  mareep: ['flaaffy', 'ampharos', 'darpharos', 'kaijuflaaffy'],
  marill: ['azumarill', 'pikablu', 'azumarillegg'],
  hoppip: ['skiploom', 'hoppot', 'jumpluff', 'bjumpluff', 'hoprake'],
  aipom: ['ambipom', 'tael', 'baipom'],
  sunkern: ['sunflora', 'sunnee', 'sunsprout', 'bsunkern', 'msunflora'],
  yanma: ['yanmega', 'byanmega'],
  wooper: ['quagsire', 'lanceffish', 'bwooper'],
  murkrow: ['honchkrow', 'bmurkrow'],
  misdreavus: ['mismagius', 'mmismagius'],
  unown: ['omegnown'],
  wobbuffet: ['wobbugeist'],
  girafarig: [
    'pyooraffe',
    'darkmare',
    'giramare',
    'giradream',
    'seafarig',
    'giradrake',
    'kaijugirafarig',
    'girafight',
  ],
  pineco: ['forretress', 'bforretress', 'beforretress'],
  dunsparce: [
    'eldsparce',
    'dunesdrill',
    'dunsparth',
    'kaijudunsparce',
    'dunschum',
  ],
  gligar: ['gliscor', 'bgligar', 'kaijugligar'],
  onix: ['msteelix', 'diamandix'],
  snubbull: ['granbull'],
  qwilfish: ['qwilshark', 'numpuff', 'fugury', 'qwilptain'],
  aqwilfish: ['navabrine', 'nucleshark', 'koilrig'],
  heracross: ['herculecross'],
  sneasel: [
    'weavile',
    'bsneasel',
    'bsneaseltwo',
    'bsneaselthree',
    'sneaviwrath',
  ],
  teddiursa: ['ursaring', 'kaijuursaring', 'bteddiursa'],
  slugma: ['magcargo', 'maglamp', 'bslugma', 'mmagcargo'],
  swinub: ['piloswine', 'mamoswine'],
  corsola: ['jcursola', 'mcorsola'],
  remoraid: [
    'octillery',
    'bremoraid',
    'moctillery',
    'boctillerytwo',
    'boctillery',
  ],
  delibird: ['ghift', 'delidelibird', 'krampird', 'krampusird'],
  houndour: ['houndoom', 'devull', 'houndhell', 'bhoundoom'],
  phanpy: ['donphan', 'bphanpy', 'mdonphan'],
  stantler: ['mstantler', 'cmstantler'],
  tyrogue: ['hitmonlee', 'hitmonchan', 'hitmontop'],
  lipp: ['jynx'],
  smoochum: ['santajynx'],
  elababee: ['electabuzz'],
  bmagby: ['magmar'],
  larvitar: ['pupitar', 'larv', 'tyranitar'],
  treecko: ['grovyle', 'btreecko', 'sceptile'],
  torchic: ['combusken', 'btorchic', 'blaziken', 'latiaziken'],
  mudkip: ['marshtomp', 'swampert'],
  poochyena: ['mightyena'],
  zigzagoon: ['linoone', 'snkdragoone'],
  wurmple: ['silcoon', 'cascoon', 'zurmex', 'beautifly', 'dustox'],
  lotad: ['lombre', 'ludicolo'],
  seedot: ['nuzleaf', 'kaijuseedot', 'shiftry'],
  taillow: ['swellow', 'taswellow'],
  wingull: ['pelipper', 'mpelipper'],
  ralts: [
    'kirlia',
    'fedorakirlia',
    'kaijuralts',
    'gardevoir',
    'gallade',
    'whoredevoir',
    'titsdevoir',
    'summervoir',
    'zgardevoir',
  ],
  surskit: ['masquerain'],
  shroomish: ['breloom', 'tbreloom', 'kaijushroomish'],
  slakoth: ['vigoroth', 'slaking', 'rotting'],
  nincada: ['ninjask', 'shedinja'],
  whismur: ['loudred', 'exploud'],
  makuhita: ['hariyama'],
  azurill: ['marill'],
  nosepass: ['probopass', 'kaijunosepass', 'bprobopass', 'mprobopass'],
  skitty: ['delcatty', 'skirona', 'mdelcatty'],
  sableye: ['msableye'],
  mawile: ['mmawile'],
  aron: ['lairon', 'aggron'],
  meditite: ['medicham', 'medijaa'],
  electrike: ['manectric', 'mmanectric'],
  plusle: ['mplusle'],
  minun: ['mminun'],
  illumise: ['illumisthicc'],
  roselia: ['roserade'],
  gulpin: ['swalot'],
  carvanha: ['sharpedo', 'sharpladon', 'sharpoat'],
  wailmer: ['wailord', 'narlord'],
  numel: ['camerupt', 'camerano'],
  torkoal: ['mtorkoal'],
  spoink: ['grumpig'],
  cspoink: ['grumboar', 'cgrumpig'],
  spinda: ['mspinda'],
  trapinch: ['vibrava', 'flygon'],
  cacnea: [
    'cacturne',
    'maractus',
    'kaijucacnea',
    'kaijumaractus',
    'waifuractus',
  ],
  swablu: ['altaria', 'altarule'],
  zangoose: ['zangol', 'snkantispiral'],
  seviper: ['sevicious', 'sevydra'],
  lunatone: ['lunighton'],
  solrock: ['galactimon', 'solaioss'],
  barboach: ['whiscash', 'mwhiscash'],
  corphish: ['crawdaunt'],
  baltoy: ['claydol'],
  lileep: ['cradily', 'kaijulileep', 'mcradily'],
  anorith: ['armaldo', 'marmaldo'],
  feebas: ['milotic'],
  kecleon: ['mkecleon'],
  shuppet: ['banette', 'fbanette', 'bbanette'],
  duskull: ['dusclops', 'dusknoir'],
  chimecho: ['winecho'],
  absol: ['aabsol'],
  wynaut: ['wobbuffet'],
  snorunt: ['glalie', 'froslass', 'mglalie'],
  spheal: ['sealeo', 'walrein'],
  clamperl: ['huntail', 'gorebyss', 'mhuntail', 'mgorebyss'],
  relicanth: ['mrelicanth'],
  luvdisc: ['mluvdiscx', 'mluvdiscy'],
  bagon: ['shelgon', 'salamence', 'sxsalamence'],
  beldum: ['metang', 'metagross'],
  latias: ['kaijulatias', 'maytias'],
  turtwig: [
    'grotle',
    'bgrotle',
    'torterra',
    'cmtorterra',
    'torcano',
    'btorterra',
  ],
  chimchar: ['monferno', 'infernape'],
  starly: ['staravia', 'staraptor'],
  bidoof: ['bibarel', 'bibastor'],
  kricketot: ['kricketune'],
  dshinx: ['luxio', 'liberinx'],
  shinx: ['bshinx', 'luxray', 'bachichi', 'bachibacchi'],
  budew: ['roselia', 'roseling', 'witherade'],
  cranidos: ['rampardos', 'bcranidos', 'brampardos'],
  shieldon: ['bastiodon'],
  burmy: ['wormadam', 'mothim'],
  combee: ['vespiquen', 'vespiguard', 'bcombee', 'bvespiquen'],
  buizel: ['floatzel'],
  cherubi: ['cherrim'],
  shellos: ['gastrodon', 'bgastrodon'],
  drifloon: ['drifblim'],
  buneary: ['lopunny', 'mlopunny'],
  glameow: ['purugly'],
  chingling: ['chimecho'],
  stunky: ['skuntank'],
  bronzor: ['bronzong', 'bbronzong'],
  bonsly: ['sudowoodo'],
  ballerine: ['mrmime'],
  gmimejr: ['gmrmime'],
  happiny: ['chansey', 'wchansey', 'kaijuhappiny', 'wblissey'],
  chatot: ['mchatot'],
  gible: ['gabite', 'bgible', 'garchomp', 'bgabite', 'bgarchomp'],
  munchlax: ['gorelax', 'snowlax', 'snorlax'],
  riolu: ['lucario', 'mlucario'],
  hippopotas: ['hippowdon', 'bhippopotas', 'bhippowdon'],
  skorupi: ['drapion'],
  croagunk: ['toxicroak', 'kaijucroagunk'],
  carnivine: ['mcarnivine', 'bcarnivine'],
  finneon: ['lumineon', 'bfinneon', 'mlumineon', 'blumineon'],
  mantyke: ['mantine', 'bsmantine', 'bcmantine'],
  snover: ['abomasnow', 'bsnover', 'abomizzard', 'babomasnow'],
  snivy: ['servine', 'serperior'],
  tepig: ['pignite', 'emboar'],
  oshawott: ['dewott', 'samurott'],
  patrat: ['watchog'],
  lillipup: ['herdier', 'stoutland', 'kaijustoutland'],
  purrloin: ['liepard'],
  pansage: ['simisage'],
  pansear: ['simisear'],
  panpour: ['simipour'],
  munna: ['musharna'],
  pidove: ['tranquill', 'unfezant'],
  blitzle: ['zebstrika', 'elesatrika'],
  roggenrola: ['boldore', 'gigalith'],
  woobat: ['swoobat', 'mswoobat'],
  drilbur: ['excadrill'],
  audino: ['melodyno', 'audinette'],
  timburr: ['gurdurr', 'conkeldurr'],
  tympole: ['palpitoad', 'seismitoad'],
  sewaddle: ['swadloon', 'leavanny'],
  venipede: ['whirlipede', 'scolipede'],
  cottonee: ['whimsicott'],
  petilil: ['lilligant'],
  sandile: ['krokorok', 'krookodile'],
  darumaka: ['darmanitan'],
  dwebble: ['crustle'],
  scraggy: ['scrafty', 'kaijuscrafty'],
  yamask: ['cofagrigus', 'urunerigus'],
  tirtouga: ['carracosta'],
  archen: ['archeops'],
  trubbish: ['garbodor', 'mgarbodor'],
  zorua: ['zoroark', 'hildaroark'],
  gothita: ['gothorita', 'gothitelle'],
  solosis: ['duosion', 'reuniclus'],
  ducklett: ['swanna'],
  vanillite: ['vanillish', 'vanilluxe'],
  deerling: ['sawsbuck'],
  karrablast: ['escavalier'],
  foongus: ['amoonguss'],
  frillish: ['jellicent'],
  alomomola: ['seraphmola', 'molashade'],
  joltik: ['galvantula', 'kaijugalvantula'],
  ferroseed: ['ferrothorn'],
  klink: ['klang', 'klinklang', 'kaijuklinklang'],
  tynamo: ['eelektrik', 'eelektross'],
  elgyem: ['beheeyem'],
  litwick: ['lampent', 'chandelure'],
  axew: ['fraxure', 'haxorus'],
  cubchoo: ['beartic'],
  shelmet: ['accelgor', 'kaijushelmet'],
  stunfisk: ['shockeel', 'mantastorm'],
  mienfoo: ['mienshao', 'mmienshao'],
  golett: ['golurk'],
  pawniard: ['bisharp'],
  rufflet: ['braviary'],
  vullaby: ['mandibuzz'],
  heatmor: ['mheatmor'],
  deino: ['zweilous', 'hydreigon'],
  larvesta: ['volcarona'],
  woot: ['woodie', 'arbrood', 'marbrood'],
  maggie: ['magman', 'lavagun', 'mlavagun'],
  steamin: ['steamer', 'steamboatle', 'msteamboatle'],
  pagie: ['swanaper', 'encyclodia', 'pagolem', 'cencyclodia'],
  smoball: ['smoman', 'snofistor', 'frostear'],
  elastim: ['bouncect', 'rubberfly'],
  cosmock: ['solrock', 'lunatone'],
  chipit: ['chokolit'],
  swirlix: ['slurpuff', 'swirlpup', 'pslurpuff', 'frostpup'],
  undlouis: ['hundead', 'zomboom', 'smobill', 'chillzie'],
  uncrow: ['haicaw'],
  rubadubb: ['splissplash'],
  bottleo: ['bottleodrake'],
  spotni: ['sateli'],
  floatube: ['drubber'],
  battie: ['capsileau'],
  tuterpill: ['caskoon', 'tutterfly'],
  tiroar: ['wheelus'],
  volcime: ['heruptin'],
  bairy: ['chairy'],
  goom: ['chewim', 'gummi'],
  cuplet: ['beaucake', 'gatteri'],
  palmetric: ['tropilightning'],
  seatie: ['tenablerus', 'elechair'],
  carpla: ['beetarp'],
  dusite: ['warchon'],
  clavies: ['tweeter', 'myosmic', 'feborius', 'snapchost', 'steamercom'],
  hompuff: ['cummunculus'],
  espionot: ['hoverot'],
  patima: ['saplom'],
  fanin: ['turbind'],
  budsee: ['sonotech'],
  creemo: ['creeposs', 'nukreep'],
  drummin: ['drumgheist'],
  grinix: ['horrorux'],
  nixox: ['namino'],
  radien: ['fissiom'],
  mopockit: ['hotpack', 'magmocket'],
  storactus: ['miracact'],
  boxy: ['chestox'],
  gargie: ['dargouille'],
  pareyemid: ['eyeluminid', 'chaosemple', 'orderymid'],
  machetit: ['buzzjaw', 'razorbash'],
  fabreel: ['facarveel'],
  orscine: ['carolden'],
  zomby: ['zombeast', 'wiondeath'],
  artsy: ['canvast'],
  eleoler: ['behemist', 'chernophoot'],
  tideno: ['flowjaw', 'warshin', 'cwarshin'],
  arod: ['atmosro'],
  cosmix: ['univax'],
  prisy: ['prismolis'],
  bergmite: ['avalugg', 'mavalugg'],
  noibat: ['noivern'],
  phantump: ['trevenant'],
  pumpkaboo: ['gourgeist', 'pumpkapie', 'soulatte'],
  litleo: ['pyroar', 'mpyroar'],
  spritzee: ['aromatisse', 'plagfume'],
  anol: ['angeist'],
  eyat: ['coraut'],
  oregi: ['canyou'],
  flufamb: ['lamcoud', 'gorale'],
  plastolphin: ['dolphottle'],
  barab: ['radicrab'],
  baifre: ['baumine'],
  microette: ['speakerro', 'boomblix'],
  otyab: ['otyash'],
  ijusgetsbigger: ['ijusgotbigger', 'ijusgotsmal'],
  fedoraz: ['euphoreye', 'mladee'],
  grasses: ['grasstacles'],
  anguar: ['archango'],
  devio: ['ledevilain'],
  sola: ['novais', 'darkole', 'smolstron'],
  bulbight: ['lightulb', 'plasbul'],
  lun: ['ryerpent', 'ryulung'],
  bunnelby: ['diggersby'],
  fletchling: ['fletchinder', 'talonflame'],
  scatterbug: ['spewpa', 'vivillon'],
  flabebe: ['floette', 'florges', 'eternalfloette'],
  skiddo: ['gogoat'],
  pancham: ['pangoro'],
  espurr: ['meowstic'],
  honedge: ['doublade', 'aegislash'],
  inkay: ['malamar'],
  binacle: ['barbaracle'],
  skrelp: ['dragalge'],
  clauncher: ['clawitzer'],
  helioptile: ['heliolisk', 'mheliolisk', 'kaijuheliolisk'],
  tyrunt: ['tyrantrum'],
  amaura: ['aurorus'],
  goomy: ['sliggoo', 'kaijugoomy', 'goodra'],
  zygarde: ['perfectzygarde'],
  iceis: ['blizzlam'],
  acies: ['eldrake', 'eldragon'],
  cosmeak: ['comistorin'],
  coolor: ['fridigor'],
  spongee: ['absorsponge'],
  melonboy: ['mellown', 'melonvile'],
  earring: ['toneout', 'xeraphox'],
  bushin: ['bushidon'],
  doit: ['juzt', 'doita'],
  spooksheet: ['strangspook', 'lynchost'],
  boxo: ['robox', 'boxtress'],
  eldrute: ['eldriz', 'eldcraftian'],
  brigo: ['phantoy'],
  belcalf: ['tauros', 'miltank', 'holeecow'],
  nanos: ['propod', 'propad'],
  mexigust: ['muchoshot'],
  playne: ['jetcraft', 'spacird'],
  lapsy: ['lapras'],
  neonee: ['neonite', 'neonazi'],
  willisp: ['willost'],
  zilly: ['godzillus'],
  raydiat: ['gammaray'],
  banor: ['hulklear'],
  zyklas: ['gachamber'],
  elding: ['eldone'],
  attot: ['reactiox'],
  nukomb: ['reqimissile'],
  goatkun: ['goatemon'],
  sushish: ['sashumish'],
  snowdoge: ['cocaiturd'],
  bongorilla: ['dongorilla'],
  diebbuk: ['diebbyuk'],
  pixall: ['pixension'],
  combug: ['buglitch'],
  smirtsnek: ['smirtrsnekek'],
  introll: ['trollternet'],
  brico: ['bricken', 'brickor'],
  trojony: ['trojorse'],
  alliswell: ['thereisonlyhell', 'helpme', 'theend', 'thankyou'],
  sixsnek: ['snatan'],
  maghat: ['wizcap', 'levelcap'],
  stando: ['tusk', 'standoge', 'tuskact3', 'standoger'],
  ness: ['skeleton'],
  nitegant: ['huntorror', 'byaklight'],
  cutehulhu: ['cthuspawn', 'cultulzu', 'cthylltulla'],
  steamos: ['steamist'],
  macat: ['jackorse'],
  kingellow: ['hasterror'],
  virurm: ['malworm'],
  finpip: ['finpelio', 'pinnister'],
  roothoot: ['owlhood', 'rootspook'],
  emcat: ['purshot', 'panthannon'],
  guttsu: ['gatsu', 'berserguts'],
  gublin: ['goblord'],
  wimpangel: ['weepangel', 'agonangel', 'seratime'],
  lunound: ['lycanmoon', 'lycanmars'],
  acroagunk: ['atoxicroak'],
  lightsy: ['syli'],
  mawcar: ['acasmoc'],
  snowpil: ['froskoon', 'rhemorice'],
  twickotweet: [
    'phantmask',
    'vampask',
    'witchise',
    'demask',
    'jackask',
    'skullask',
    'lagoonask',
    'ayymask',
    'zombmask',
    'clownask',
    'mummyask',
    'wolfmansk',
    'invisimask',
  ],
  ningice: ['ningenice'],
  pikipek: ['trumbeak', 'toucannon', 'kaijutoucannon'],
  crabrawler: ['crabominable'],
  morelull: ['shiinotic'],
  yungoos: ['gumshoos', 'kaijugumshoos'],
  seapi: ['seahog'],
  eldri: ['eldreye'],
  rowlet: ['dartrix', 'decidueye'],
  litten: ['torracat', 'incineroar'],
  popplio: ['brionne', 'primarina', 'kaijuprimarina'],
  grubbin: ['charjabug', 'vikavolt'],
  cutiefly: ['ribombee', 'kaijucutiefly'],
  rockruff: ['dlycanroc', 'nlycanroc', 'ulycanroc'],
  mareanie: ['toxapex'],
  mudbray: ['mudsdale'],
  dewpider: ['araquanid'],
  fomantis: ['lurantis'],
  salandit: ['salazzle'],
  stufful: ['bewear', 'kaijustufful'],
  bounsweet: ['steenee', 'tsareena'],
  wimpod: ['golisopod'],
  sandygast: ['palossand'],
  pyukumuku: ['kaijupyukumuku', 'pyukuluku'],
  typenull: ['silvally'],
  jangmoo: ['hakamoo', 'kommoo'],
  cosmog: ['cosmoem', 'lunala', 'solgaleo'],
  nihilego: ['nymbiosego', 'motherbeast'],
  peacon: ['pearoyal'],
  cragite: ['canyonite'],
  spirus: ['splague'],
  lunafake: ['fonighton'],
  moonse: ['lunarat'],
  amagikarp: ['agyarados'],
  adratini: ['adragonair', 'adragonite'],
  poisapp: ['toxapple'],
  burgite: ['icendless'],
  asandshrew: ['asandslash'],
  arattata: ['araticate'],
  avulpix: ['aninetales'],
  ameowth: ['apersian', 'aperrserker', 'gameowth', 'mapersian'],
  agrimer: ['amuk'],
  aparas: ['aparasect'],
  akoffing: ['aweezing'],
  bmagikarp: ['bgyarados'],
  adiglett: ['adugtrio'],
  ageodude: ['agraveler', 'agolem'],
  apoochyena: ['amightyena'],
  wendigi: ['wendigore'],
  onigi: ['onigirice'],
  sloggoth: ['sloggeroth', 'elsloggeroth', 'husloggeroth'],
  pmagikarp: ['pgyarados'],
  bartle: ['torteel', 'knood'],
  mageno: ['magamen', 'mageyser'],
  mistice: ['phantice', 'serpentice'],
  slinka: ['slinpis', 'slinkala'],
  cornird: ['cornosera', 'regacaw'],
  rockon: ['mossolem', 'frostolem'],
  coneet: ['concoona', 'stingcano'],
  nothyp: ['serpentina'],
  conix: ['csteelix', 'mcsteelix'],
  baitish: ['fishor'],
  nymphad: ['dryasin', 'naiqua', 'aulpriland', 'sylphind', 'lampeath'],
  stalig: ['stalagfright'],
  drafly: ['drakefly'],
  anguille: ['saphireau'],
  foggot: ['foggeam'],
  nout: ['donout', 'sonout', 'lonout', 'treblout'],
  twirlano: ['seedin'],
  diog: ['demonig'],
  wigglearth: ['dooworm'],
  dogzygarde: ['zygarde'],
  cellzygarde: ['corezygarde', 'dogzygarde'],
  chypper: ['enchip', 'systerus'],
  demoncake: ['devilcak'],
  ambroel: ['ambrosine'],
  pawno: ['rookower', 'chevak', 'bishess', 'queeness', 'kingo'],
  bubblet: [
    'bubloform',
    'cobrubble',
    'drabon',
    'leobble',
    'burble',
    'turble',
    'elebubble',
  ],
  wock: ['stowin', 'winolith'],
  tomatea: ['chillyip', 'pepperella', 'bause'],
  cloudlet: [
    'clounight',
    'acidoud',
    'rainoud',
    'sunnound',
    'frwind',
    'clawnd',
    'thundoud',
    'clwister',
  ],
  tridler: ['trirayd', 'trinvasio'],
  ayyliem: ['ayymao'],
  cybirb: ['cypecker'],
  ufowoah: ['ufolien', 'ufoear'],
  cristo: ['flashard', 'prishard', 'phanshard', 'storshard'],
  tadpal: ['frogpal'],
  marir: ['castleet'],
  cornel: ['grancorn'],
  shalight: ['lumix', 'shadrix', 'lidra', 'dardra', 'shadight'],
  lettucee: ['saladman'],
  sliwa: ['cawice'],
  ballim: ['helift'],
  shrul: ['smoov', 'sporeel'],
  bonnacalf: ['bonaflatuen'],
  viria: [
    'verius',
    'viroison',
    'feaverus',
    'cuberus',
    'shockerus',
    'snoozerus',
  ],
  bonfen: ['fitree', 'campyre'],
  cobret: ['serfric', 'comfstrictor'],
  spiortal: ['spiortex'],
  grifawk: ['grifallen', 'griffisen'],
  poipole: ['naganadel'],
  acaterpie: ['ametapod', 'abutterfree'],
  amantyke: ['amantine'],
  aoddish: ['agloom', 'avileplume'],
  agrowlithe: ['aarcanine'],
  atogepi: ['atogetic', 'atogekiss'],
  rathy: ['rathor', 'rathlos', 'rathiana'],
  sakuyaid: ['beachsakuya'],
  cirnai: ['santacirno'],
  patchician: ['beachpatchi'],
  amissingno: ['misssingo'],
  kokana: ['kasanagi', 'kasanova'],
  balistagon: ['supercannon'],
  memee: ['memeo', 'memaster'],
  smilepup: ['smilehound'],
  flambear: ['volbear', 'dynabear'],
  cruz: ['aqua', 'aquaria'],
  trifox: ['vulpix'],
  tangel: ['tangela'],
  golppy: ['goldeen'],
  sunmola: ['molaee', 'anchorage', 'grotess', 'molaugg'],
  para: ['paras'],
  spidette: ['tuhedd'],
  chiks: ['doduo'],
  meowsy: ['meowth'],
  rinring: ['bellboyant'],
  minicorn: ['ponyta'],
  grimey: ['grimer'],
  gohng: ['topmonhit'],
  puddi: ['growlithe'],
  lefmew: ['dandemew', 'cottomew'],
  tigrette: ['electiger', 'gaotora'],
  kurstraw: ['pangshi'],
  wolfman: ['warwolf'],
  urchall: ['spurchin'],
  ahole: ['crachole', 'cracholiath'],
  staresh: ['stargem'],
  eggit: ['eggotto', 'friedack'],
  cbulbasaur: ['civysaur', 'cvenusaur'],
  ccharmander: ['ccharmeleon', 'ccharizard'],
  csquirtle: ['cwartortle', 'cblastoise'],
  asolosis: ['aduosion', 'areuniclus'],
  adrifloon: ['adrifblim'],
  adarumaka: ['adarmanitan'],
  tissoe: ['kleenot'],
  breadamo: ['toasted'],
  toater: ['toastaem'],
  fletchice: ['cluckatrice', 'roosteratrice'],
  birttle: ['amorvian'],
  koap: ['hatos', 'unhichaos'],
  suckert: ['swirlia', 'lolichap'],
  flwood: ['woopeck'],
  extinguil: ['putout'],
  soobu: ['sebushus'],
  magu: ['magbru'],
  zombry: ['charund', 'spiombie', 'jombey'],
  sunisk: ['solfish'],
  sewan: ['sewantor'],
  pyrork: ['artifire', 'artiwyrk'],
  rogo: ['rogyst'],
  spino: ['spinga'],
  soundagon: ['sonardrake'],
  carplosion: ['carpetbomb'],
  finish: ['bludgreigon'],
  salember: ['axofire', 'searamander'],
  squinky: ['inkuid'],
  lemmong: ['lemmongade'],
  voodoll: ['voodem'],
  calculus: ['calculusus'],
  maskett: ['visagelle'],
  blimy: ['hidenblim'],
  eikishiki: ['beachshikieiki'],
  rogodo: ['apollolar', 'marsarrior', 'artania', 'venusess', 'merquick'],
  babirys: ['suriv'],
  shoison: ['battacid'],
  aliceoll: ['beachalice'],
  arachoe: ['backscorpion'],
  blolocute: ['bloculo', 'blolossod'],
  humowl: ['mothmowl'],
  windoh: ['winblow', 'winpane', 'peekindow'],
  bunn: ['draguette', 'subwaydon'],
  predorb: ['seerorb', 'prophorb'],
  tapistle: ['blopire'],
  larvick: ['tickood'],
  smoodie: ['coocamodie'],
  rockandy: ['crystandy', 'cracandy'],
  seeare: ['feasume'],
  marpet: ['flarpet'],
  dnaby: ['dnaelix', 'dnanium'],
  supaninteno: ['cubegamo', 'wiilly', 'threediesh'],
  lightip: ['flameup'],
  nerober: ['nerobaltah'],
  traino: ['strain', 'electrain', 'shinkantrain'],
  rumiarkness: ['santarumia'],
  sworesh: ['marlencin'],
  grenir: ['marvelamp'],
  mystiarrow: ['santamystia'],
  bowser: [
    'bowserkoobala',
    'mechabowserstatue',
    'bowserstatue',
    'furybowser',
    'shrowser',
    'drbowser',
    'cakebowser',
    'bowletta',
    'skylanderbowser',
    'amiibobowser',
    'paperbowser',
    'kartbowser',
    'metalbowser',
    'darkbowser',
    'bowsette',
    'drybowser',
    'retrobowser',
    'megadragonbowser',
    'meowser',
    'darkskylanderbowser',
  ],
  pendrasp: ['hillipod', 'axelasp'],
  wrigglight: ['santawriggle'],
  veloprey: ['velodrome'],
  utsuclear: ['beachutsuho'],
  dalo: ['balremon'],
  lagannech: ['gurrenlagannech'],
  meltan: ['melmetal'],
  parsenvy: ['santaparsee'],
  kisumket: ['santakisume'],
  fishember: ['searish'],
  desound: ['descreech'],
  chillizar: ['frozark', 'frizard'],
  catace: ['catface'],
  amimejr: ['amrmime'],
  apurrloin: ['aliepard'],
  acacnea: ['acacturne'],
  snowtorb: ['snowtrode'],
  atreecko: ['agrovyle', 'asceptile'],
  atorchic: ['acombusken', 'ablaziken'],
  amudkip: ['amarshtomp', 'aswampert'],
  shockra: ['barkanite'],
  hbuneary: ['hlopunny', 'mhlopunny'],
  coyot: ['coyotears'],
  mario: ['metalmario', 'goldmario'],
  indianelephant: ['smtpurski', 'smtgirimehkala', 'smtganesha'],
  suncrab: ['solcrab'],
  ittybatty: ['zubat'],
  chargra: ['chargradon', 'chargroar'],
  gyao: ['gyaoon'],
  squi: ['squink', 'squidrill'],
  cheepa: ['beeta'],
  sumorog: ['kungfrog'],
  wadgon: ['waterake', 'wateragon'],
  elizidol: ['selizidol'],
  gooseling: ['gooseloose'],
  wooloo: ['dubwool', 'woolshep', 'wololo'],
  corviknight: ['gcorviknight'],
  drednaw: ['gdrednaw'],
  gossifleur: ['eldegoss'],
  mariantoinette: ['amariantoinette'],
  rodac: ['rodactyl'],
  impidimp: ['morgrem', 'grimmsnarl'],
  yamper: ['boltund'],
  tortuagel: ['aeongel', 'archongel'],
  rockodile: ['crocwistul'],
  rolycoly: ['carkoal', 'coalossal', 'locoalmotive'],
  alcremie: ['galcremie', 'thiccremie'],
  darkyo: ['darkyoun', 'shubniggurother'],
  glassbol: ['aquariuol', 'terraol'],
  voltbyor: ['voltorb'],
  tuberm: ['swimmerm'],
  tuberf: ['swimmerf'],
  enderite: ['endmeran', 'endershulk', 'endragon'],
  maverock: ['chillrock', 'overock', 'blastrock'],
  godsol: ['corruptedsol'],
  asmoochum: ['ajynx', 'majynx'],
  hearhild: ['heartlenine', 'nobotile', 'unlion', 'dreagamorph', 'royickish'],
  ezigzagoon: ['elinoone', 'eobstagoon'],
  pengui: ['pengemperor', 'albinguin'],
  gzigzagoon: ['glinoone', 'obstagoon'],
  lilsaibah: ['saibah'],
  aseedot: ['anuzleaf', 'ashiftry'],
  sphealedge: ['sealeoedge', 'walreinedge'],
  gcharmander: ['gcharmeleon', 'gcharizard'],
  flolyp: ['flyongolyp'],
  lusfairy: [
    'mylph',
    'lustubust',
    'gothot',
    'torappu',
    'elsnow',
    'wyrmaiden',
    'domineko',
    'mammarina',
    'youkawaii',
  ],
  migus: ['migoggoth', 'amigoggoth'],
  stillnut: ['mrstillnut', 'lordstillnut'],
  sgeodude: ['sgraveler', 'sgolem'],
  steamea: ['stweams', 'steamnie'],
  ndratini: ['ndragonair', 'ndragonite'],
  snakeny: ['serpeople', 'yigsnake'],
  hydeep: ['deepone', 'dagonther', 'mothydra'],
  killnut: ['mrkillnut', 'lordkillnut'],
  deltrune: ['jestevil', 'karmris', 'susully', 'prinsiel'],
  firepire: ['cthugyre'],
  necroli: ['necrolili', 'necrolilith', 'swimnecrolilith'],
  gooei: ['gooarm', 'gooswole'],
  chanaroy: ['chanarang', 'chanoken'],
  dbounsweet: ['dsteenee', 'dtsareena'],
  earbuzz: ['phornet'],
  protecdoll: ['proteknight'],
  skittiglock: ['skittigang'],
  arrokuda: ['barraskewda'],
  dreamulus: ['duodreamulus', 'dreamungus', 'dreamare'],
  drabite: ['biteragon', 'herculeagon'],
  drowsleep: ['sleepevil', 'dreamarx'],
  pizzaur: ['pizzaurex'],
  drewi: ['dreamwi'],
  ebolette: ['ebolass', 'autisma', 'nursebola'],
  itsy: ['bitsy'],
  dementad: ['lombression', 'lunaticolo'],
  pijammin: ['tendream'],
  nebrownie: ['galactcake'],
  broodhort: ['eihortli'],
  cthoniurm: ['shuddermell'],
  starvipup: ['hungier', 'hollowland', 'loyaland'],
  emojicon: ['cursedcon', 'xokcon', 'noocon', 'crycon'],
  qwailmer: ['qwailord'],
  opticusufo: ['optulzu', 'retulzu', 'spatulzu'],
  wphantump: ['wtrevenant'],
  yeerby: [
    'noseer',
    'fabdeer',
    'psyelk',
    'suprago',
    'moosid',
    'stormdler',
    'stantler',
  ],
  grookey: [
    'thwackey',
    'zimbaga',
    'rillaboom',
    'kongdom',
    'saunarilla',
    'somalorilla',
  ],
  scorbunny: [
    'raboot',
    'cindemiga',
    'cinderace',
    'astrobunny',
    'scorknight',
    'helialope',
    'heakazuking',
  ],
  sobble: [
    'drizzile',
    'depremeleon',
    'inteleon',
    'drakobble',
    'societrex',
    'suiceleon',
  ],
  withrew: ['malevia', 'rosemalum'],
  egguish: ['friendfly', 'deleggme'],
  stabra: ['kapierce', 'alakatana'],
  slimee: [
    'kingslimee',
    'darlime',
    'metalslimee',
    'bubbleslime',
    'healslimee',
    'seaslimee',
    'kingdarlime',
    'metalkingslimee',
    'liquidmetalslime',
    'cureslimee',
  ],
  gponyta: ['grapidash'],
  gstunfisk: ['stuntrap'],
  rookiedie: ['corvisquire', 'corviknight', 'corviknighteen'],
  skwovet: ['greedent'],
  nicket: ['thievul'],
  blipbug: ['dottler', 'orbeetle'],
  chewtle: ['drednaw'],
  sizzlipede: ['centiskorch'],
  galmeowth: ['galpersian', 'perrserker'],
  milcery: ['alcremie'],
  applin: ['flapple', 'appletun'],
  gcorsola: ['cursola'],
  hattena: ['hattrem', 'hatterene', 'shatterene'],
  cufant: ['copperajah'],
  toxel: ['toxtricity', 'lktoxtricity'],
  silicobra: ['sandaconda'],
  gyamask: ['runerigus'],
  indeedee: ['maideedee'],
  snom: ['frosmoth'],
  clobbopus: ['grapploct'],
  dreepy: ['drakloak', 'dragapult'],
  wsnover: ['wabomasnow'],
  mimejr: ['mrrime'],
  tdyamask: ['tdcofagrigus'],
  tgyamask: ['tgcofagrigus'],
  tzyamask: ['tzcofagrigus'],
  tmlyamask: ['tikcofagrigus'],
  tduskull: ['tdusclops', 'duscelle'],
  tspoink: ['tgrumpig'],
  gfarfetchd: ['sirfetchd'],
  gdarumaka: ['gdarmanitan'],
  baidy: ['audino'],
  wbaidy: ['waudino', 'wmelodyno'],
  stunfish: ['stunfisk', 'gstunfisk'],
  cgeodude: ['cgraveler', 'cgolem'],
  syclar: ['syclant'],
  protowatt: ['krilowatt'],
  embirch: ['flarelm', 'pyroak'],
  breezi: ['fidgit'],
  rebble: ['tactite', 'stratagem'],
  pancosmic: ['pancalamity', 'pancallous'],
  aloby: ['alomomola'],
  wbasculin: ['anglereist'],
  privatyke: ['arghonaut'],
  smvoodoll: ['voodoom'],
  nohface: ['kitsunoh'],
  monohm: ['duohm', 'cyclohm'],
  phagus: ['nexaphago'],
  h1e1: ['eboli'],
  devilby: ['devilmar', 'hellmortar'],
  corneen: ['maze'],
  livepunch: ['firepuncher', 'kinopunch', 'pumpkinopunch'],
  ballbu: ['snowbun', 'snoware', 'snowugg'],
  dunspa: ['dunspit', 'dunsnek'],
  quailnote: ['choruseph', 'dootbirb'],
  cocoobag: ['mothca'],
  blarvitar: ['btyranitar'],
  pluffle: ['kerfluffle'],
  mumbao: ['jumbao'],
  floatoy: ['camainoe', 'naviathan'],
  fawnifer: ['electrelk', 'caribolt'],
  smogecko: ['smoguana', 'smokomodo'],
  swirlpool: ['coribalis', 'snaelstrom'],
  wdeino: ['wzweilous', 'whydreigon'],
  jooney: ['santajoon'],
  shionhobo: ['santashion'],
  dmareep: ['dflaaffy', 'dampharos'],
  gswablu: ['galtaria'],
  mummeem: ['pharoammy', 'momummy'],
  roven: ['infernace'],
  hbagon: ['hshelgon', 'hsalamence'],
  dmeowth: ['dpersian'],
  huneehi: ['huneyler'],
  felekid: ['felectabuzz', 'felectivire'],
  emagby: ['emagmar', 'emagmortar'],
  bou: ['boukka', 'bouquetke'],
  midger: ['fingle', 'faakyu'],
  blobby: ['blobuff'],
  dmunna: ['dmusharna', 'muspecta'],
  tdarumaka: ['tdarmanitan'],
  fagyamask: ['yangelic'],
  fsmoochum: ['fjynx', 'jybaba'],
  hubulbasaur: ['huivysaur', 'huvenusaur'],
  hucharmander: ['hucharmeleon', 'hucharizard'],
  husquirtle: ['huwartortle', 'hublastoise'],
  hucaterpie: ['humetapod', 'fuggirl', 'hubutterfree'],
  huweedle: ['hukakuna', 'hubeedrill'],
  hupidgey: ['hupidgeotto', 'hupidgeot'],
  hurattata: ['huraticate'],
  huspearow: ['hufearow'],
  hupikachu: ['huraichu'],
  husandshrew: ['husandslash'],
  hunidoranfe: ['hunidorina', 'hunidoqueen'],
  hunidoranma: ['hunidorino', 'hunidoking'],
  huclefairy: ['huclefable'],
  hujigglypuff: ['huwigglytuff'],
  huzubat: ['hugolbat'],
  huoddish: ['hugloom', 'huvileplume'],
  huparas: ['huparasect'],
  huvenonat: ['huvenomoth'],
  hudiglett: ['hudugtrio'],
  humeowth: ['hupersian'],
  hupsyduck: ['hugolduck'],
  humankey: ['huprimeape'],
  hugrowlithe: ['huarcanine'],
  hupoliwag: ['hupoliwhirl', 'hupoliwrath'],
  huabra: ['hukadabra', 'hualakazam'],
  humachop: ['humachoke', 'humachamp'],
  hubellsprout: ['huweepinbell', 'huvictreebel'],
  hutentacool: ['hutentacruel'],
  hugeodude: ['hugraveler', 'hugolem'],
  huslowpoke: ['huslowbro'],
  humagnemite: ['humagneton'],
  hudoduo: ['hudodrio'],
  huseel: ['hudewgong'],
  hugrimer: ['humuk'],
  hushellder: ['hucloyster'],
  hudrowzee: ['huhypno'],
  hukrabby: ['hukingler'],
  huexeggcute: ['huexeggutor'],
  hucubone: ['humarowak'],
  hukoffing: ['huweezing'],
  huhorsea: ['huseadra'],
  hugoldeen: ['huseaking'],
  hustaryu: ['hustarmie'],
  humagikarp: ['hugyarados'],
  hueevee: ['huvaporeon', 'hujolteon', 'huflareon'],
  hukabuto: ['hukabutops'],
  hudratini: ['hudragonair', 'hudragonite'],
  zbagon: ['zshelgon', 'zsalamence'],
  snkgrimreaper: ['ironreaper'],
  houndsour: ['headdoom'],
  skinskin: ['snkeyeeye', 'snkgorgegorge'],
  elecharge: ['electabugs', 'shogunvire'],
  miaby: ['miasmar', 'magmori'],
  irivatar: ['metalitar', 'zyranizila'],
  snowkitty: ['frozcatty'],
  yeutdoom: ['wobdoomer'],
  evidisc: ['demohate'],
  rustum: ['rustang', 'rustegross'],
  blackuto: ['darkutops'],
  mewby: ['mutagon'],
  thorita: ['thornleef', 'thornium', 'mawnium'],
  cleffgar: ['clegoyle', 'garfable'],
  dirtkrow: ['lichkrow'],
  telson: ['telshark'],
  polihag: ['poliworm', 'poliwraith', 'snkzombified'],
  moulder: ['yuck'],
  roteen: ['seatyrant'],
  zombicater: ['deaderant'],
  brimshrew: ['toxislash'],
  nidoblood: ['rubirina', 'rosaqueen'],
  metalran: ['cyborino', 'mechaking'],
  burstmadio: ['blastmadio'],
  calfby: ['bombelgia', 'donnangus', 'ramshaker'],
  cinderco: ['cinderprise', 'radiorange'],
  mysteryegg: [
    'secretegg',
    'hyperegg',
    'suicune',
    'entei',
    'raikou',
    'celebi',
    'unownfinity',
  ],
  glitchlett: ['glitchtrio', 'glitchtet'],
  hombone: ['hombeast'],
  kenchira: ['kenchukuo', 'kenkopper', 'kenkaras'],
  boilbasaur: ['shrivlsaur', 'vivosaur'],
  rotmander: ['charmeworm', 'lichizard', 'snkdragon'],
  oozle: ['entrailtle', 'bleedtoise'],
  decarill: ['graveill', 'azombarill'],
  psylet: ['psypig'],
  seimenkongou: ['amonra'],
  burnasaur: ['embersaur', 'vulcasaur'],
  seamander: ['seameleon', 'sealizard'],
  fertle: ['rootortle', 'grasstoise'],
  caterpebb: ['minepod', 'boulderfree'],
  geodle: ['prikuna', 'bristrill'],
  fridgey: ['fridgeotto', 'fridgeot'],
  rottata: ['roticate'],
  ghastata: ['ghasticate'],
  mechans: ['mecharbok'],
  pikacoal: ['raicoal'],
  bushrew: ['bushlash'],
  boxiranfe: ['boxirina', 'boxiqueen'],
  boxiranma: ['boxirino', 'boxiking'],
  clefair: ['inflable'],
  vulstyx: ['sinistales'],
  jigglisect: ['arachtuff'],
  sinjbat: ['volbat', 'explobat'],
  odprong: ['turboon', 'panelplume'],
  faaras: ['omnisect'],
  fernonat: ['fernomoth'],
  meowxie: ['magisian'],
  sluduck: ['taintduck'],
  mankember: ['flameape'],
  mandiwag: ['mandiwhirl', 'mandiwrath', 'mandirit'],
  abrark: ['cutabra', 'shinigazam'],
  zenchop: ['zenchoke', 'zenchamp'],
  bellpowder: ['cannonbell', 'chernobell'],
  tentapunch: ['tentabrawl'],
  aquadude: ['coraller', 'golacier'],
  ponytamp: ['rapidouse'],
  stalagnemite: ['stalagneton', 'stalagcola'],
  farganc: ['sirganc'],
  slowslab: ['slowsidian', 'slowspike'],
  drillduo: ['drilldrio'],
  seewage: ['pollugong'],
  grimag: ['mukma'],
  celesder: ['cloystar'],
  goomly: ['paragoomer', 'goomgar'],
  eelix: ['eelectrix'],
  ectozee: ['hypnoplasm'],
  krabbune: ['kraggler'],
  frientorb: ['luxutrode'],
  swarmute: ['exeggunest'],
  cublade: ['marowarior'],
  lickoral: ['reeficoral'],
  sparkking: ['shockking'],
  drachorn: ['dracdon', 'dracperior'],
  basiney: ['blissea'],
  lazzmela: ['lazzplug'],
  horsteed: ['steedra', 'kingsdale'],
  golbee: ['beeking'],
  starite: ['starau'],
  sickler: ['scizorch'],
  necrablast: ['necratomic'],
  plasgar: ['plasmission'],
  chilikarp: ['flarados'],
  threevee: ['drilleon', 'insecteon', 'caireon', 'barbeon', 'senseion'],
  sandanice: ['sandasnow'],
  leviuto: ['leviatops'],
  pixini: ['pixinair', 'pixinite'],
  mspain: ['monsterpain'],
  ujamer: ['ujadalord'],
  holloach: ['illexash'],
  swooloo: ['sdubwool'],
  trapunk: ['motorava', 'gangon'],
  birbley: ['ridteen', 'ridleyuge'],
  mbboo: ['kingboo'],
  facefugger: ['chestburste', 'xenoalien'],
  garfielf: ['gorefielf', 'scpee3166'],
  ffnutkin: ['ffsouleater', 'ffskulleater'],
  trollel: ['elaboruse'],
  wetloon: ['aqualoon', 'jubiloon'],
  loleye: ['oppeye', 'thicclops'],
  alcohog: ['swineyard'],
  hillarge: ['bigliff', 'gigantain'],
  frospidey: ['froscorpio'],
  moustab: ['daggerat', 'sworodent'],
  boebii: ['bowaii', 'bowtesque'],
  ploop: ['dungus', 'poolossus'],
  gullbage: ['albatrash'],
  gruppy: ['barkoon', 'stingnarl'],
  pinnint: ['pinsochist', 'badmini'],
  pengwarn: ['banguin'],
  pantom: ['punchortz', 'lingereist'],
  sparroof: ['spastle', 'spalcazar'],
  slugar: ['escarbun'],
  pizzauro: ['mozzarex', 'pepperoari'],
  nyuvel: ['nyuvel2', 'nyuvel0'],
  yellynth: ['magiynth', 'orchesynth'],
  twiggerd: ['trunkannon'],
  schnozard: ['schnormous'],
  squbble: ['kraclean'],
  molstub: ['molstache', 'molbeardo'],
  beanoy: ['oniogre'],
  cuffy: ['whippain', 'collatrix'],
  hairjog: ['kerajog'],
  senteddi: ['urscort'],
  tardough: ['breadiot', 'pastiot', 'cookiot'],
  salsik: ['sikrak', 'sikteria'],
  teevz: ['teepod', 'cuppatee'],
  oymayt: ['yuwotmayt'],
  pinana: ['peelngas'],
  splug: ['adaplug', 'cabilisk'],
  flopple: ['buktopple', 'corottle'],
  fleap: ['flitchi'],
  shlario: ['razario'],
  snotto: ['boglob', 'fluinter'],
  ovilock: ['alkeydin'],
  clownim: ['tentaclown'],
  tinna: ['skeletuna'],
  capseal: ['nurseal', 'manursee'],
  marmin: ['marmight'],
  chairor: ['throgon'],
  hologg: ['holectric'],
  clagma: ['lavalve', 'volclamno'],
  trichic: ['squaychic', 'pentragon'],
  tabbee: ['tabbumble'],
  eaglass: ['threaglass'],
  gouwheel: ['hauntaxi', 'bussacre'],
  chubbirb: ['birbutter'],
  goleg: ['figoleg'],
  fagworm: ['cigraworm'],
  powdillar: ['grencoon', 'exploth'],
  nimbud: ['bonskai'],
  slasherpie: ['metalblud', 'scorpiofree'],
  intestinela: ['entrailgrowth'],
  hidelra: ['huldire'],
  ballough: ['hunballun'],
  solotl: ['astrolotl'],
  dmagikarp: ['dgyarados'],
  miasva: ['miasmaw'],
  cmsnivy: ['cmservine', 'cmsnivy', 'cmserperior'],
  seqola: ['sequoisola'],
  zotsune: ['zoroterasu'],
  bristik: ['airantula'],
  hsnorunt: ['hglalie', 'hfroslass'],
  sephiroth: ['safersephiroth'],
  poppip: ['skipop', 'yumsicle'],
  yarrbull: ['swashbull'],
  moemura: ['mmhomura'],
  dlostsoul: ['betalostsoul'],
  doomhellknight: ['baronofhell'],
  arachnotron: ['dspiderdemon'],
  sitryvern: ['sitragon', 'dracelium'],
  shyguy: ['shyflyguy', 'shyguyghost', 'shygal'],
  koopatroopa: ['koopaparatroopa', 'drybones'],
  bobomb: ['kingbobomb'],
  crwutemate: ['coommate'],
  wackqualitydoge: ['wackmuscleman', 'wackchad', 'wackvirgin', 'sprite007'],
  huboilbasaur: ['hushrivlsaur', 'huvivosaur'],
  hurotmander: ['hucharmeworm', 'hulichizard', 'husnkdragon'],
  huoozle: ['huentrailtle', 'hubleedtoise'],
  huslasherpie: ['humetalblud', 'huscorpiofree'],
  huzombicater: ['hudeaderant'],
  hubrimshrew: ['hutoxislash'],
  hunidoblood: ['hurubirina', 'hurosaqueen'],
  humetalran: ['hucyborino', 'humechaking'],
  huclegoyle: ['hugarfable'],
  hupolihag: ['hupoliworm', 'hupoliwraith'],
  humoulder: ['huyuck'],
  huroteen: ['huseatyrant'],
  hublackuto: ['hudarkutops'],
  humewby: ['humutagon'],
  huhombone: ['huhombeast'],
  hustabra: ['hukapierce', 'hualakatana'],
  huglitchlett: ['huglitchtrio', 'huglitchtet'],
  toxitung: ['toxilicky', 'toxilikk'],
  impychu: ['huraitan', 'devilchu', 'raitan'],
  pupstel: ['canistel', 'lupinstel'],
  wponyta: ['wrapidash'],
  bskiddo: ['bgogoat'],
  glute: ['bute', 'nute'],
  walts: ['jungia', 'gardevoid', 'shinigami'],
  tricko: ['grovile', 'tyrantile'],
  franichic: ['franiken', 'blazistein'],
  fangkip: ['marshfang', 'swamphorror'],
  smoquill: ['quilfog', 'thermasion', 'mosslosion'],
  blinodile: ['purblinaw', 'impairgatr', 'irradialigtr'],
  veloci: ['velociadult'],
  ptero: ['pteroadult'],
  trice: ['triceadult'],
  composo: ['compsoadult'],
  iguano: ['iguanoadult'],
  plesio: ['plesioadult'],
  abel: ['yethrall', 'saslash'],
  epslime: ['declime'],
  bliqu: ['gequi', 'alquri'],
  tase: ['podcoon', 'cooltase'],
  shizard: ['shicoon', 'epicshizard'],
  seleli: ['armoreen'],
  flaon: ['manleon', 'furyon'],
  magid: ['voltine', 'magrunk'],
  furegul: ['metagul', 'ultagel'],
  rabbiny: ['rabbeast'],
  healmadio: ['starmadio'],
  missingmadio: ['m4d10'],
  impamadio: ['baphomadio'],
  mlpspike: ['spowps'],
  hgrowlithe: ['harcanine'],
  kecleovyl: ['kecleotile'],
  shubaducklett: ['shubaswanna'],
  horrorpatrick: ['thetorturedone'],
  smtjackfrost: [
    'smtblackfrost',
    'smtkingfrost',
    'smtqueenfrost',
    'smtdemoneeho',
    'smtlucifroz',
    'smtacefrost',
    'smtwendigo',
  ],
  doomeyesonic: ['blackdoomsonic', 'devildoomsonic'],
  deathleechsonic: ['blackwarriorsonic', 'blackoaksonic', 'blacktroopsonic'],
  blackwingsonic: ['blackhawksonic'],
  chaosonic: [
    'herochao',
    'darkchao',
    'sonicchao',
    'shadowchao',
    'amychao',
    'tailschao',
    'knuckleschao',
    'chaoschao',
  ],
  bladeliger: ['waifuliger'],
  smtkaiwan: ['smtdecarabia'],
  smtpetitfrost: ['smtjackfrost'],
  smtpascal: ['smtcerberus'],
  smtpixie: ['smthighpixie'],
  smtmechi: [
    'smtshock',
    'smtparamese',
    'smtnidhoggr',
    'smthareofinaba',
    'smthomunculus',
    'smtsnappy',
  ],
  smtmorax: ['smtmoloch'],
  smtmithras: ['smtmithra'],
  smtorc: ['smthorkos', 'smtorcus'],
  smtasura: ['smtasherah'],
  smtbeelzebub: ['waifubeelzebub'],
  smtlucifera: ['smtluciferd'],
  smtpreta: ['smtpisaca'],
  smtfrog: ['smtbael'],
  wacknshellos: ['wackngastrodon'],
  wacksshellos: ['wacksgastrodon'],
  analgae: ['rectreem'],
  arabomb: ['iguallah', 'lizakbar'],
  ejacasm: ['hosajack', 'condoom'],
  squirrap: ['gampster'],
  kengeon: ['frieden', 'corooster'],
  curicrawl: ['gutsicoon', 'gutsifly'],
  larvades: ['proboskito', 'venowatt'],
  clovour: ['kuuroba', 'chanolour'],
  nauseon: ['hazmate', 'ebolable'],
  lanshil: ['middril', 'shurismash'],
  maymay: ['memenace'],
  armando: ['muscledude', 'tripecs'],
  semdrop: ['semrust', 'semdemen', 'semmush'],
  furnazi: ['finasoven'],
  troubait: ['tulure', 'monstrap', 'baitmaster'],
  pixila: ['fairileon'],
  wedgard: ['knokedge'],
  ribbizap: ['bulbfrog'],
  chompest: ['vaultevour'],
  masdawg: ['pasdawg'],
  spanke: ['anaconduke', 'ballboa'],
  fishnism: ['sjwhale'],
  chezetta: ['mozzamazel'],
  krokling: ['krokizon'],
  conchilla: ['haremit'],
  coolcube: ['tankube', 'fabkube'],
  smogaroben: ['smoxilon', 'smogars'],
  bacub: ['urswine'],
  moostatic: ['mooshock'],
  tvirusby: ['licky', 'nemmy', 'albwesker', 'gravediggy'],
  metaltyrannomon: ['rustyrannomon'],
  xveemon: ['imperialdramon'],
  stingmon: ['imperialdramonb'],
  veemon: ['xveemon'],
  wormmon: ['stingmon'],
  lucemon: ['lucemonfm'],
  bendy: ['inkbendy'],
  impmon: ['beelzemon'],
  kuriboh: ['wingedkuriboh'],
  meltrego: ['summeryllis'],
  hokusailhu: ['hokusaibah'],
  tsumemon: ['keramon', 'chrysalimon', 'infermon', 'diablomon'],
};
